-- Query for RL001
'' AS foracid
,'' AS cust_cr_pref_pcnt
,'' AS cust_dr_pref_pcnt
,'' AS id_cr_pref_pcnt
,'' AS id_dr_pref_pcnt
,'' AS repricing_plan
,'' AS peg_frequency_in_months
,'' AS peg_frequency_in_days
,'' AS int_route_flg
,'' AS acct_crncy_code
,'' AS sol_id
,'' AS gl_sub_head_code
,'' AS schm_code
,'' AS cif_id
,'' AS acct_opn_date
,'' AS sanct_lim
,'' AS ledg_num
,'' AS sector_code
,'' AS sub_sector_code
,'' AS purpose_of_advn
,'' AS nature_of_advn
,'' AS free_code_3
,'' AS sanct_ref_num
,'' AS lim_sanct_date
,'' AS sanct_levl_code
,'' AS lim_exp_date
,'' AS sanct_auth_code
,'' AS loan_paper_date
,'' AS op_acid
,'' AS op_crncy_code
,'' AS op_sol_id
,'' AS dmd_satisfy_mthd
,'' AS lien_on_oper_acct_flg
,'' AS ds_rate_code
,'' AS int_tbl_code
,'' AS int_on_p_flg
,'' AS pi_on_pdmd_ovdu_flg
,'' AS pdmd_ovdu_eom_flg
,'' AS int_on_idmd_flg
,'' AS pi_on_idmd_ovdu_flg
,'' AS idmd_ovdu_eom_flg
,'' AS xfer_eff_date
,'' AS cum_norm_int_amt
,'' AS cum_pen_int_amt
,'' AS cum_addnl_int_amt
,'' AS liab_as_on_xfer_eff_date
,'' AS rephasement_principal
,'' AS interest_calc_upto_date_dr
,'' AS rep_shdl_date
,'' AS rep_perd_mths
,'' AS rep_perd_days
,'' AS pd_flg
,'' AS pd_xfer_date
,'' AS prv_to_pd_gl_sub_head_code
,'' AS int_suspense_amt
,'' AS penal_int_suspense_amt
,'' AS chrge_off_flg
,'' AS chrge_off_date
,'' AS chrge_off_principal
,'' AS pending_interest
,'' AS principal_recovery
,'' AS interest_recovery
,'' AS source_deal_code
,'' AS disburse_deal_code
,'' AS apply_late_fee_flg
,'' AS late_fee_grace_perd_mnths
,'' AS late_fee_grace_perd_days
,'' AS upfront_instl_coll
,'' AS num_advance_instlmnt
,'' AS upfront_instl_amt
,'' AS dpd_cntr
,'' AS sum_principal_dmd_amt
,'' AS payoff_flg
,'' AS xclude_for_comb_stmt
,'' AS stmt_cif_id
,'' AS xfer_cycle_str
,'' AS bank_irr_rate
,'' AS value_of_asset
,'' AS acct_occp_code
,'' AS borrower_category_code
,'' AS mode_of_advn
,'' AS type_of_advn
,'' AS guar_cover_code
,'' AS industry_type
,'' AS free_code_1
,'' AS free_code_2
,'' AS free_code_4
,'' AS free_code_5
,'' AS free_code_6
,'' AS free_code_7
,'' AS free_code_8
,'' AS free_code_9
,'' AS free_code_10
,'' AS acct_locn_code
,'' AS crfile_ref_id
,'' AS dicgc_fee_pcnt
,'' AS last_compound_date
,'' AS daily_comp_int_flg
,'' AS calc_ovdu_int_flg
,'' AS ei_perd_start_date
,'' AS ei_perd_end_date
,'' AS irr_rate
,'' AS adv_int_amount
,'' AS amortized_amount
,'' AS booked_upto_date_dr
,'' AS adv_int_coll_upto_date
,'' AS accrual_rate
,'' AS int_rate_based_on_sanct_lim
,'' AS int_rest_freq
,'' AS int_rest_basis
,'' AS chrg_route_flg
,'' AS final_disb_flg
,'' AS auto_reshdl_after_hldy_perd
,'' AS tot_num_defmnts
,'' AS num_defmnt_curr_shdl
,'' AS peg_review_date
,'' AS pi_based_on_outstanding
,'' AS charge_off_type
,'' AS def_appl_int_rate_flg
,'' AS def_appl_int_rate
,'' AS deferred_int_amt
,'' AS auto_reshdl_not_allowed
,'' AS reshdl_overdue_prin
,'' AS reshdl_overdue_int
,'' AS loan_type
,'' AS payoff_reason_code
,'' AS rel_deposit_acid
,'' AS last_aod_aos_date
,'' AS refin_sanct_date
,'' AS refin_amt
,'' AS sbsdy_acid
,'' AS sbsdy_agency
,'' AS prin_sbsdy_claimed_date
,'' AS subs_act_code
,'' AS aod_aos_type
,'' AS refin_sanct_num
,'' AS refin_ref_num
,'' AS refin_avld_date
,'' AS prin_sbsdy_amt
,'' AS prin_sbsdy_rcvd_date
,'' AS pre_process_fee
,'' AS act_code
,'' AS probation_prd_mths
,'' AS probation_prd_days
,'' AS comp_date_flg
,'' AS disc_rate_flg
,'' AS int_coll_flg
,'' AS ps_despatch_mode
,'' AS acct_mgr_user_id
,'' AS mode_of_oper_code
,'' AS ps_freq_type
,'' AS ps_freq_week_num
,'' AS ps_freq_week_day
,'' AS ps_freq_start_dd
,'' AS ps_freq_hldy_stat
,'' AS pb_ps_code
,'' AS ps_next_due_date
,'' AS fixedterm_mnths
,'' AS fixedterm_years
,'' AS min_int_pcnt_dr
,'' AS max_int_pcnt_dr
,'' AS install_income_ratio
,'' AS product_group
,'' AS free_text
,'' AS linked_acct_id
,'' AS delinq_reshdl_mthd_flg
,'' AS total_num_of_switchover
,'' AS non_starter_flg
,'' AS float_int_tbl_code
,'' AS float_repricing_freq_mnths
,'' AS float_repricing_freq_days
,'' AS singleemi_tenordiff_flg
,'' AS iban_number
,'' AS ias_code
,'' AS topup_acid
,'' AS topup_type
,'' AS negotiated_rate_dr
,'' AS penal_prod_mthd_flg
,'' AS penal_rate_mthd_flg
,'' AS full_penal_mthd_flg
,'' AS hldy_prd_frm_first_disb_flg
,'' AS ei_schm_flg
,'' AS ei_method
,'' AS ei_formula_flg
,'' AS nrml_hldy_perd_mnths
,'' AS hldy_perd_int_flg
,'' AS hldy_perd_int_amt
,'' AS rshdl_tenor_ei_flg
,'' AS rshdl_disbt_flg
,'' AS rshdl_rate_chng_flg
,'' AS rshdl_prepay_flg
,'' AS rshdl_amt_flg
,'' AS rephase_capitalize_int
,'' AS rephase_carry_ovdu_dmds
,'' AS type_of_instlmnt_comb
,'' AS cap_emi_flg
,'' AS emicap_deferred_int
,'' AS start_dfmnt_mnth
,'' AS num_mnths_deferred
,'' AS chnl_cr_pref_pcnt
,'' AS chnl_dr_pref_pcnt
,'' AS channel_id
,'' AS channel_level_code
,'' AS instlmnt_grace_perd_term_flg
,'' AS instlmnt_grace_perd_mnths
,'' AS shift_instlmnt_flg
,'' AS include_matu_date_flg
,'' AS rule_code
,'' AS cum_capitalize_fees
,'' AS upfront_instl_int_amt
,'' AS recall_flg
,'' AS recall_date
,'' AS ps_diff_freq_rel_party_flg
,'' AS swift_diff_freq_rel_party_flg
,'' AS penal_int_tbl_code
,'' AS penal_pref_pcnt
,'' AS resp_acct_ref_no
,'' AS int_version
,'' AS add_type
,'' AS phone_type
,'' AS email_type
,'' AS accrued_penal_int_recovery
,'' AS penal_int_recovery
,'' AS coll_int_recovery
,'' AS coll_penal_int_recovery
,'' AS markup_int_rate_appl_flg
,'' AS preferred_cal_base
,'' AS purchase_ref
,'' AS frez_code
,'' AS frez_reason_code
,'' AS RL001_232
,'' AS RL001_233
,'' AS RL001_234
,'' AS RL001_235
,'' AS RL001_236
,'' AS RL001_237
,'' AS RL001_238
,'' AS RL001_239
,'' AS RL001_240
,'' AS RL001_241
,'' AS RL001_242
,'' AS RL001_243
,'' AS RL001_244
,'' AS RL001_245
,'' AS RL001_246
,'' AS RL001_247
,'' AS RL001_248
,'' AS RL001_249
,'' AS RL001_250
,'' AS RL001_251
,'' AS RL001_252
,'' AS RL001_253
,'' AS RL001_254
,'' AS RL001_255
,'' AS RL001_256
,'' AS RL001_257
,'' AS RL001_258
,'' AS RL001_259
,'' AS RL001_260
,'' AS RL001_261
,'' AS RL001_262
,'' AS RL001_263
,'' AS RL001_264
,'' AS RL001_265
,'' AS RL001_266
,'' AS RL001_267
,'' AS RL001_268
,'' AS RL001_269
,'' AS RL001_270
,'' AS RL001_271
,'' AS RL001_272
,'' AS RL001_273
,'' AS RL001_274
,'' AS RL001_275
,'' AS RL001_276
,'' AS RL001_277
,'' AS RL001_278
,'' AS RL001_279
,'' AS RL001_280
,'' AS RL001_281
,'' AS RL001_282
,'' AS RL001_283
,'' AS RL001_284
,'' AS RL001_285
,'' AS RL001_286
,'' AS RL001_287
,'' AS RL001_288
,'' AS RL001_289
,'' AS RL001_290
,'' AS RL001_291
,'' AS RL001_292
,'' AS RL001_293
,'' AS RL001_294
,'' AS RL001_295
,'' AS RL001_296
,'' AS RL001_297
,'' AS RL001_298
,'' AS RL001_299
,'' AS RL001_300
,'' AS RL001_301
,'' AS RL001_302
,'' AS RL001_303
,'' AS RL001_304
,'' AS RL001_305
,'' AS RL001_306
,'' AS RL001_307
,'' AS RL001_308
,'' AS RL001_309
,'' AS RL001_310
,'' AS RL001_311
,'' AS RL001_312
,'' AS RL001_313
,'' AS RL001_314
,'' AS RL001_315
,'' AS RL001_316
,'' AS RL001_317
,'' AS RL001_318
,'' AS RL001_319
,'' AS RL001_320
,'' AS RL001_321
,'' AS RL001_322
,'' AS RL001_323
,'' AS RL001_324
,'' AS RL001_325
,'' AS RL001_326
,'' AS RL001_327
,'' AS RL001_328
,'' AS RL001_329
,'' AS RL001_330
,'' AS RL001_331
,'' AS RL001_332
,'' AS RL001_333
,'' AS RL001_334
,'' AS RL001_335
,'' AS RL001_336
,'' AS RL001_337
,'' AS RL001_338
,'' AS RL001_339
,'' AS RL001_340
,'' AS RL001_341
,'' AS RL001_342
,'' AS RL001_343
,'' AS RL001_344
,'' AS RL001_345
,'' AS RL001_346
,'' AS RL001_347
,'' AS RL001_348