IF OBJECT_ID('tempdb.dbo.#FinalMaster', 'U') IS NOT NULL
  DROP TABLE #FinalMaster;
IF OBJECT_ID('tempdb.dbo.#FinalMaster', 'U') IS NOT NULL
  DROP TABLE #FinalMaster;
SELECT *
INTO #FinalMaster
FROM
	(
		SELECT DISTINCT
		 [Name]
		,ClientCode
		,AcType
		,BranchCode
		,Obligor
		,AcOpenDate
		,MainCode
		,CyCode
		,ROW_NUMBER() OVER( PARTITION BY ClientCode ORDER BY AcOpenDate,MainCode) AS SerialNumber
		--INTO #FinalMaster
		FROM Master WITH (NOLOCK)
		WHERE IsBlocked NOT IN ('C','o')
		--ORDER BY ClientCode
	) AS t 
WHERE t.SerialNumber = 1 ORDER BY 1;

IF OBJECT_ID('tempdb.dbo.#ClientName', 'U') IS NOT NULL
  DROP TABLE #ClientName;
IF OBJECT_ID('tempdb.dbo.#ClientName', 'U') IS NOT NULL
  DROP TABLE #ClientName;
  
SELECT ClientCode, CASE WHEN CHARINDEX('/',Name)  > 0 THEN SUBSTRING(Name,0,CHARINDEX('/',Name)) 
ELSE Name
END as Name,Name AS Orig_Name
INTO #ClientName
FROM ClientTable

SELECT dt.ORGKEY
,dt.CIFID
,dt.ENTITYTYPE
,dt.CUST_TYPE_CODE
,dt.SALUTATION_CODE
,dt.CUST_FIRST_NAME
,dt.CUST_MIDDLE_NAME
,dt.CUST_LAST_NAME
,dt.PREFERREDNAME
,dt.SHORT_NAME
,CASE WHEN dt.CUST_DOB > GETDATE() THEN REPLACE(REPLACE(CONVERT(VARCHAR,'01-Jan-1985',106), ' ','-'), ',','') ELSE dt.CUST_DOB END AS CUST_DOB
,dt.GENDER
,dt.OCCUPATION_CODE
,dt.NATIONALITY
,dt.NATIVELANGTITLE
,dt.NATIVELANGNAME
,dt.DOCUMENT_RECIEVED
,dt.STAFFFLAG
,dt.STAFFEMPLOYEEID
,dt.MANAGER
,dt.CUSTOMERNREFLAG
,dt.DATEOFBECOMINGNRE
,dt.CUSTOMERMINOR
,dt.MINORGAURDIANID
,dt.MINOR_GUARD_CODE
,dt.MINOR_GUARD_NAME
,dt.REGION
,dt.PRIMARY_SERVICE_CENTRE
,dt.RELATIONSHIPOPENINGDATE
,dt.STATUS_CODE
,dt.CUSTSTATUSCHGDATE
,dt.HOUSEHOLDID
,dt.HOUSEHOLDNAME
,dt.CRNCY_CODE_RETAIL
,dt.RATING_CODE
,dt.RATINGDATE
,dt.CUST_PREF_TILL_DATE
,dt.TDS_TBL_CODE
,dt.INTRODUCERID
,dt.INTRODUCERSALUTATION
,dt.INTRODUCERNAME
,dt.INTRODUCERSTATUSCODE
,dt.OFFLINE_CUM_DEBIT_LIMIT
,dt.CUST_TOT_TOD_ALWD_TIMES
,dt.CUST_COMMU_CODE
,dt.CARD_HOLDER
,dt.CUST_HLTH
,dt.CUST_HLTH_CODE
,dt.TFPARTYFLAG
,dt.PRIMARY_SOL_ID
,dt.CONSTITUTION_REF_CODE
,dt.CUST_OTHR_BANK_CODE
,dt.CUST_FIRST_ACCT_DATE
,dt.CHRG_LEVEL_CODE
,dt.CHRG_DR_FORACID
,dt.CHRG_DR_SOL_ID
,dt.CUST_CHRG_HISTORY_FLG
,dt.COMBINED_STMT_REQD
,dt.LOANS_STMT_TYPE
,dt.TD_STMT_TYPE
,dt.COMB_STMT_CHRG_CODE
,dt.DESPATCH_MODE
,dt.CS_LAST_PRINTED_DATE
,dt.CS_NEXT_DUE_DATE
,dt.ALLOW_SWEEPS
,dt.PS_FREQ_TYPE
,dt.PS_FREQ_WEEK_NUM
,dt.PS_FREQ_WEEK_DAY
,dt.PS_FREQ_START_DD
,dt.PS_FREQ_HLDY_STAT
,dt.ENTITY_TYPE
,dt.LINKEDRETAILCIF
,dt.HSHLDUFLAG
,dt.SMALL_STR1
,dt.SMALL_STR2
,dt.SMALL_STR3
,dt.SMALL_STR4
,dt.SMALL_STR5
,dt.SMALL_STR6
,dt.SMALL_STR7
,dt.SMALL_STR8
,dt.SMALL_STR9
,dt.SMALL_STR10
,dt.MED_STR1
,dt.MED_STR2
,dt.MED_STR3
,dt.MED_STR4
,dt.MED_STR5
,dt.MED_STR6
,dt.MED_STR7
,dt.MED_STR8
,dt.MED_STR9
,dt.MED_STR10
,dt.LARGE_STR1
,dt.LARGE_STR2
,dt.LARGE_STR3
,dt.LARGE_STR4
,dt.LARGE_STR5
,dt.DATE1
,dt.DATE2
,dt.DATE3
,dt.DATE4
,dt.DATE5
,dt.DATE6
,dt.DATE7
,dt.DATE8
,dt.DATE9
,dt.DATE10
,dt.NUMBER1
,dt.NUMBER2
,dt.NUMBER3
,dt.NUMBER4
,dt.NUMBER6
,dt.NUMBER5
,dt.NUMBER7
,dt.NUMBER8
,dt.NUMBER9
,dt.NUMBER10
,dt.DECIMAL1
,dt.DECIMAL2
,dt.DECIMAL3
,dt.DECIMAL4
,dt.DECIMAL5
,dt.DECIMAL6
,dt.DECIMAL7
,dt.DECIMAL8
,dt.DECIMAL9
,dt.DECIMAL10
,dt.CORE_CUST_ID
,dt.PERSONTYPE
,dt.CUST_LANGUAGE
,dt.CUST_STAFF_STATUS
,dt.PHONE
,dt.EXTENSION
,dt.FAX
,dt.FAX_HOME
,dt.PHONE_HOME
,dt.PHONE_HOME2
,dt.PHONE_CELL
,dt.EMAIL_HOME
,dt.EMAIL_PALM
,dt.EMAIL
,dt.CITY
,dt.PREFERREDCHANNELID
,dt.CUSTOMERRELATIONSHIPNO
,dt.RELATIONSHIPVALUE
,dt.CATEGORY
,dt.NUMBEROFPRODUCTS
,dt.RELATIONSHIPMGRID
,dt.RELATIONSHIPCREATEDBYID
,dt.URL
,dt.STATUS
,dt.INDUSTRY
,dt.PARENTORG
,dt.COMPETITOR
,dt.SICCODE
,dt.CIN
,dt.DESIGNATION
,dt.ASSISTANT
,dt.INTERNALSCORE
,dt.CREDITBUREAUSCOREVALIDITY
,dt.CREDITBUREAUSCORE
,dt.CREDITBUREAUREQUESTDATE
,dt.CREDITBUREAUDESCRIPTION
,dt.MAIDENNAMEOFMOTHER
,dt.ANNUALREVENUE
,dt.REVENUEUNITS
,dt.TICKERSYMBOL
,dt.AUTOAPPROVAL
,dt.FREEZEPRODUCTSALE
,dt.RELATIONSHIPFIELD1
,dt.RELATIONSHIPFIELD2
,dt.RELATIONSHIPFIELD3
,dt.DELINQUENCYFLG
,dt.CUSTOMERNREFLG
,dt.COMBINEDSTATEMENTFLG
,dt.CUSTOMERTRADE
,dt.PLACEOFBIRTH
,dt.COUNTRYOFBIRTH
,dt.PROOFOFAGEFLAG
,dt.PROOFOFAGEDOCUMENT
,dt.NAMESUFFIX
,dt.MAIDENNAME
,dt.CUSTOMERPROFITABILITY
,dt.CURRENTCREXPOSURE
,dt.TOTALCREXPOSURE
,dt.POTENTIALCRLINE
,dt.AVAILABLECRLIMIT
,dt.CREDITSCOREREQUESTEDFLAG
,dt.CREDITHISTORYREQUESTEDFLAG
,dt.GROUPID
,dt.FLG1
,dt.FLG2
,dt.FLG3
,dt.ALERT1
,dt.ALERT2
,dt.ALERT3
,dt.RELATIONSHIPOFFER1
,dt.RELATIONSHIPOFFER2
,dt.DTDATE1
,dt.DTDATE2
,dt.DTDATE3
,dt.DTDATE4
,dt.DTDATE5
,dt.DTDATE6
,dt.DTDATE7
,dt.DTDATE8
,dt.DTDATE9
,dt.AMOUNT1
,dt.AMOUNT2
,dt.AMOUNT3
,dt.AMOUNT4
,dt.AMOUNT5
,dt.STRFIELD1
,dt.STRFIELD2
,dt.STRFIELD3
,dt.STRFIELD4
,dt.STRFIELD5
,dt.STRFIELD6
,dt.STRFIELD7
,dt.STRFIELD8
,dt.STRFIELD9
,dt.STRFIELD10
,dt.STRFIELD11
,dt.STRFIELD12
,dt.STRFIELD13
,dt.STRFIELD14
,dt.STRFIELD15
,dt.USERFLAG1
,dt.USERFLAG2
,dt.USERFLAG3
,dt.USERFLAG4
,dt.MLUSERFIELD1
,dt.MLUSERFIELD2
,dt.MLUSERFIELD3
,dt.MLUSERFIELD4
,dt.MLUSERFIELD5
,dt.MLUSERFIELD6
,dt.MLUSERFIELD7
,dt.MLUSERFIELD8
,dt.MLUSERFIELD9
,dt.MLUSERFIELD10
,dt.MLUSERFIELD11
,dt.NOTES
,dt.PRIORITYCODE
,dt.CREATED_FROM
,dt.CONSTITUTION_CODE
,dt.STRFIELD16
,dt.STRFIELD17
,dt.STRFIELD18
,dt.STRFIELD19
,dt.STRFIELD20
,dt.STRFIELD21
,dt.STRFIELD22
,dt.AMOUNT6
,dt.AMOUNT7
,dt.AMOUNT8
,dt.AMOUNT9
,dt.AMOUNT10
,dt.AMOUNT11
,dt.AMOUNT12
,dt.INTFIELD1
,dt.INTFIELD2
,dt.INTFIELD3
,dt.INTFIELD4
,dt.INTFIELD5
,dt.NICK_NAME
,dt.MOTHER_NAME
,dt.FATHER_HUSBAND_NAME
,dt.PREVIOUS_NAME
,dt.LEAD_SOURCE
,dt.RELATIONSHIP_TYPE
,dt.RM_GROUP_ID
,dt.RELATIONSHIP_LEVEL
,dt.DSA_ID
,dt.PHOTOGRAPH_ID
,dt.SECURE_ID
,dt.DELIQUENCYPERIOD
,dt.ADDNAME1
,dt.ADDNAME2
,dt.ADDNAME3
,dt.ADDNAME4
,dt.ADDNAME5
,dt.OLDENTITYCREATEDON
,dt.OLDENTITYTYPE
,dt.OLDENTITYID
,dt.DOCUMENT_RECEIVED
,dt.SUSPEND_NOTES
,dt.SUSPEND_REASON
,dt.BLACKLIST_NOTES
,dt.BLACKLIST_REASON
,dt.NEGATED_NOTES
,dt.NEGATED_REASON
,dt.SEGMENTATION_CLASS
,dt.NAME
,dt.MANAGEROPINION
,dt.INTROD_STATUS
,dt.NATIVELANGCODE
,dt.MINORATTAINMAJORDATE
,dt.NREBECOMINGORDDATE
,dt.STARTDATE
,dt.ADD1_FIRST_NAME
,dt.ADD1_MIDDLE_NAME
,dt.ADD1_LAST_NAME
,dt.ADD2_FIRST_NAME
,dt.ADD2_MIDDLE_NAME
,dt.ADD2_LAST_NAME
,dt.ADD3_FIRST_NAME
,dt.ADD3_MIDDLE_NAME
,dt.ADD3_LAST_NAME
,dt.ADD4_FIRST_NAME
,dt.ADD4_MIDDLE_NAME
,dt.ADD4_LAST_NAME
,dt.ADD5_FIRST_NAME
,dt.ADD5_MIDDLE_NAME
,dt.ADD5_LAST_NAME
,dt.DUAL_FIRST_NAME
,dt.DUAL_MIDDLE_NAME
,dt.DUAL_LAST_NAME
,dt.CUST_COMMUNITY
,dt.CORE_INTROD_CUST_ID
,dt.INTROD_SALUTATION_CODE
,dt.TDS_CUST_ID
,dt.NAT_ID_CARD_NUM
,dt.PSPRT_ISSUE_DATE
,dt.PSPRT_DET
,dt.PSPRT_EXP_DATE
,dt.CRNCY_CODE
,dt.PREF_CODE
,dt.INTROD_STATUS_CODE
,dt.NATIVELANGTITLE_CODE
,dt.GROUPID_CODE
,dt.SECTOR
,dt.SUBSECTOR
,dt.CUSTCREATIONMODE
,dt.FIRST_PRODUCT_PROCESSOR
,dt.INTERFACE_REFERENCE_ID
,dt.CUST_HEALTH_REF_CODE
,dt.TDS_CIFID
,dt.PREF_CODE_RCODE
,dt.CUST_SWIFT_CODE_DESC
,dt.IS_SWIFT_CODE_OF_BANK
,dt.NATIVELANGCODE_CODE
,dt.CREATEDBYSYSTEMID
,dt.PREFERREDEMAILTYPE
,dt.PREFERREDPHONE
,dt.FIRST_NAME_NATIVE
,dt.MIDDLE_NAME_NATIVE
,dt.LAST_NAME_NATIVE
,dt.SHORT_NAME_NATIVE
,dt.FIRST_NAME_NATIVE1
,dt.MIDDLE_NAME_NATIVE1
,dt.LAST_NAME_NATIVE1
,dt.SHORT_NAME_NATIVE1
,dt.SECONDARYRM_ID
,dt.TERTIARYRM_ID
,dt.SUBSEGMENT
,dt.ACCESSOWNERGROUP
,dt.ACCESSOWNERSEGMENT
,dt.ACCESSOWNERBC
,dt.ACCESSOWNERAGENT
,dt.ACCESSASSIGNEEAGENT
,dt.CHARGELEVELCODE
,dt.INTUSERFIELD1
,dt.INTUSERFIELD2
,dt.INTUSERFIELD3
,dt.INTUSERFIELD4
,dt.INTUSERFIELD5
,dt.STRUSERFIELD1
,dt.STRUSERFIELD2
,dt.STRUSERFIELD3
,dt.STRUSERFIELD4
,dt.STRUSERFIELD5
,dt.STRUSERFIELD6
,dt.STRUSERFIELD7
,dt.STRUSERFIELD8
,dt.STRUSERFIELD9
,dt.STRUSERFIELD10
,dt.STRUSERFIELD11
,dt.STRUSERFIELD12
,dt.STRUSERFIELD13
,dt.STRUSERFIELD14
,dt.STRUSERFIELD15
,dt.STRUSERFIELD16
,dt.STRUSERFIELD17
,dt.STRUSERFIELD18
,dt.STRUSERFIELD19
,dt.STRUSERFIELD20
,dt.STRUSERFIELD21
,dt.STRUSERFIELD22
,dt.STRUSERFIELD23
,dt.STRUSERFIELD24
,dt.STRUSERFIELD25
,dt.STRUSERFIELD26
,dt.STRUSERFIELD27
,dt.STRUSERFIELD28
,dt.STRUSERFIELD29
,dt.STRUSERFIELD30
,dt.DATEUSERFIELD1
,dt.DATEUSERFIELD2
,dt.DATEUSERFIELD3
,dt.DATEUSERFIELD4
,dt.DATEUSERFIELD5
,dt.BACKENDID
,dt.RISK_PROFILE_SCORE
,dt.RISK_PROFILE_EXPIRY_DATE
,dt.PREFERREDPHONETYPE
,dt.PREFERREDEMAIL
,dt.NOOFCREDITCARDS
,dt.REASONFORMOVINGOUT
,dt.COMPETITORPRODUCTID
,dt.OCCUPATIONTYPE
,dt.BANK_ID
,dt.ZAKAT_DEDUCTION
,dt.ASSET_CLASSIFICATION
,dt.CUSTOMER_LEVEL_PROVISIONING
,dt.ISLAMIC_BANKING_CUSTOMER
,dt.PREFERREDCALENDAR
,dt.IDTYPER1
,dt.IDTYPER2
,dt.IDTYPER3
,dt.IDTYPER4
,dt.IDTYPER5
,dt.CUST_LAST_NAME_ALT1
,dt.CUST_FIRST_NAME_ALT1
,dt.CUST_MIDDLE_NAME_ALT1
,dt.STRFIELD6_ALT1
,dt.NAME_ALT1
,dt.SHORT_NAME_ALT1
,dt.ISEBANKINGENABLED
,dt.PURGEFLAG
,dt.SUSPENDED
,dt.BLACKLISTED
,dt.NEGATED
,dt.ACCOUNTID
,dt.ADDRESS_LINE1
,dt.ADDRESS_LINE2
,dt.ADDRESS_LINE3
,dt.STATE
,dt.COUNTRY
,dt.ZIP
,dt.BOCREATEDBYLOGINID
,dt.SUBMITFORKYC
,dt.KYC_REVIEWDATE
,dt.KYC_DATE
,dt.RISKRATING
,dt.SENIORCITIZEN
,dt.SENCITIZENAPPLICABLEDATE
,dt.SENCITIZENCONVERSIONFLAG
,dt.FOREIGNACCTAXREPORTINGREQ
,dt.FOREIGNTAXREPORTINGCOUNTRY
,dt.FOREIGNTAXREPORTINGSTATUS
,dt.LASTFOREIGNTAXREVIEWDATE
,dt.NEXTFOREIGNTAXREVIEWDATE
,dt.FATCAREMARKS
,dt.DATEOFDEATH
,dt.DATEOFNOTIFICATION
,dt.PHYSICAL_STATE
,dt.UNIQUEIDNUMBER

FROM (
SELECT DISTINCT --top 1000
'R0' + t1.ClientCode AS ORGKEY
,'R0' + t1.ClientCode AS CIFID
,'Customer' AS ENTITYTYPE
,'Retail' AS CUST_TYPE_CODE
,CASE WHEN lower(t2.Gender) = 'f' OR lower(Salutation) = 'mrs' THEN 'MS.'
 WHEN lower(t2.Gender) = 'm' OR lower(Salutation) = 'mr' THEN 'MR.' 
 ELSE 'M/S.' end SALUTATION_CODE
,
CASE WHEN isnull(SUBSTRING(CName.Name,1,CHARINDEX(' ',LTRIM(RTRIM(CName.Name)))),'.') = '' THEN '.'
 ELSE isnull(SUBSTRING(ltrim(rtrim(CName.Name)),1,charindex(' ',ltrim(rtrim(CName.Name)))),'.')
 END AS CUST_FIRST_NAME

,CASE WHEN charindex('/',CName.Orig_Name) > 0 THEN CName.Orig_Name
 ELSE
	 replace(replace (ltrim(rtrim(CName.Name)), SUBSTRING(ltrim(rtrim(CName.Name)),0,charindex(' ',ltrim(rtrim(CName.Name)))) , ''),reverse(SUBSTRING(reverse(ltrim(rtrim(CName.Name))),0,charindex(' ',reverse(ltrim(rtrim(CName.Name)))))),'') 
 END AS CUST_MIDDLE_NAME
,CASE WHEN isnull(reverse(SUBSTRING(reverse(ltrim(rtrim(CName.Name))),0,charindex(' ',reverse(ltrim(rtrim(CName.Name)))))),'.') = '' THEN '.'
 ELSE isnull(reverse(SUBSTRING(reverse(ltrim(rtrim(CName.Name))),0,charindex(' ',reverse(ltrim(rtrim(CName.Name)))))),'.')
 END as CUST_LAST_NAME

,CASE WHEN isnull(SUBSTRING(CName.Name,1,CHARINDEX(' ',LTRIM(RTRIM(CName.Name)))),'.') = '' THEN '.'
 ELSE isnull(SUBSTRING(ltrim(rtrim(CName.Name)),1,charindex(' ',ltrim(rtrim(CName.Name)))),'.')
 END AS PREFERREDNAME
,CASE WHEN t1.Name = '' OR t1.Name is NULL THEN 'MIGR' ELSE LEFT(t1.Name,10) END AS SHORT_NAME
--,CASE WHEN t2.DateOfBirth IS NULL OR t2.DateOfBirth >= GETDATE() THEN REPLACE(REPLACE(CONVERT(VARCHAR,'01-Jan-1985',106), ' ','-'), ',','') 
--ELSE
--REPLACE(REPLACE(CONVERT(VARCHAR,t2.DateOfBirth,106), ' ','-'), ',','') 
,CASE WHEN ctrlt.Today <= t2.DateOfBirth AND t1.AcType='0B' THEN REPLACE(REPLACE(CONVERT(VARCHAR,dbo.f_GetRomanDate(DatePart(Day,t2.DateOfBirth),DatePart(MONTH,t2.DateOfBirth),DatePart(YEAR,t2.DateOfBirth)),106), ' ','-'), ',','')
      WHEN t2.DateOfBirth > ctrlt.Today THEN REPLACE(REPLACE(CONVERT(VARCHAR,dbo.f_GetRomanDate(DatePart(Day,t2.DateOfBirth),DatePart(MONTH,t2.DateOfBirth),DatePart(YEAR,t2.DateOfBirth)),106), ' ','-'), ',','')
     WHEN t2.DateOfBirth IS NULL OR t2.DateOfBirth = '' THEN REPLACE(REPLACE(CONVERT(VARCHAR,'01-Jan-1985',106), ' ','-'), ',','')
	--WHEN t2.DateOfBirth >= ctrlt.Today THEN REPLACE(REPLACE(CONVERT(VARCHAR,'01-Jan-1985',106), ' ','-'), ',','')
     ELSE REPLACE(REPLACE(CONVERT(VARCHAR,t2.DateOfBirth,106), ' ','-'), ',','')
END AS CUST_DOB
,CASE WHEN t2.Gender = 'M' THEN 'M'
WHEN t2.Gender = 'F' THEN 'F'
ELSE 'O'
END AS GENDER
,'' AS OCCUPATION_CODE
,CASE WHEN ct.ISOCode = '' OR ct.ISOCode IS NULL THEN 'NP' ELSE ct.ISOCode END AS NATIONALITY		
,'' AS NATIVELANGTITLE
,'' AS NATIVELANGNAME
,'Y' AS DOCUMENT_RECIEVED
,CASE WHEN t2.ClientCode = fe.ClientCode  THEN 'Y'
ELSE 'N'
END AS STAFFFLAG
,CASE WHEN t2.ClientCode = fe.ClientCode THEN convert(varchar,EmpId)
ELSE ''
END AS STAFFEMPLOYEEID		--need to be changed after BPD as Pumori employee_id need to be matched in Finacle
,'FIVUSR' AS MANAGER  -- Default value added as per understanding with bank
,CASE WHEN t4.CustType IN('CB','NB','XB','UB','AF','DB','MB','OB','RB','VB','WC') THEN 'Y'
ELSE 'N'
END AS CUSTOMERNREFLAG
,CASE WHEN t4.CustType IN('CB','NB','XB','UB','AF','DB','MB','OB','RB','VB','WC') THEN REPLACE(REPLACE(CONVERT(VARCHAR,t1.AcOpenDate,106), ' ','-'), ',','') ELSE '' END AS DATEOFBECOMINGNRE
,ISNULL(REPLACE(tminor.CUSTOMERMINOR,'','N'),'N') AS CUSTOMERMINOR  -- changed
,CASE WHEN tminor.CUSTOMERMINOR = 'Y' THEN 'CIFMINOR' 
ELSE '' 
END AS MINORGAURDIANID --changed
,CASE WHEN tminor.CUSTOMERMINOR = 'Y' THEN 'F' 
ELSE '' 
END AS MINOR_GUARD_CODE  
,CASE WHEN tminor.CUSTOMERMINOR = 'Y' THEN 'Default Value' 
ELSE '' 
END AS MINOR_GUARD_NAME		--need value for Default Value 
,'MIGR' AS REGION			--need to be changed as per BPD
,RIGHT(SPACE(5)+CAST(t1.BranchCode AS VARCHAR(5)),5) AS PRIMARY_SERVICE_CENTRE
,REPLACE(REPLACE(CONVERT(VARCHAR,t1.AcOpenDate,106), ' ','-'), ',','') AS RELATIONSHIPOPENINGDATE
,CASE WHEN t2.ClientStatus IS NULL OR t2.ClientStatus = '' THEN 'ACTVE'
WHEN t2.ClientStatus = 'D' THEN 'DCSED'
WHEN t2.ClientStatus = 'L' THEN 'LUNAT'
WHEN t2.ClientStatus = 'u' THEN 'UNRE'
WHEN t2.ClientStatus = 'w' THEN 'WANT'
WHEN t2.ClientStatus = 's' THEN 'SUSP'
WHEN t2.ClientStatus = 'Z' THEN 'STOP'
WHEN t2.ClientStatus = 'N' THEN 'ACTVE'
--WHEN t2.ClientStatus = '1' THEN 'ACTVE'
WHEN t2.ClientStatus = 'b' THEN 'WANT'
ELSE 'ACTVE' END AS STATUS_CODE		
,'' AS CUSTSTATUSCHGDATE
,'' AS HOUSEHOLDID
,'' AS HOUSEHOLDNAME
,'NPR' AS CRNCY_CODE_RETAIL
,CASE WHEN lower(t2.Key_Risk_Grade ) like 'l%' THEN 'LOW'
WHEN lower(t2.Key_Risk_Grade ) LIKE 'm%' THEN 'MEDUM'
WHEN lower(t2.Key_Risk_Grade) LIKE 'h%' THEN 'HIGH'
else 'MIGR'  end as RATING_CODE
,'' AS RATINGDATE
,'' AS CUST_PREF_TILL_DATE
,'A' AS TDS_TBL_CODE
,'' AS INTRODUCERID
,'' AS INTRODUCERSALUTATION
,'INTRODUCER1' AS INTRODUCERNAME  -- Default value as per the understanding from bank
,'' AS INTRODUCERSTATUSCODE
,'' AS OFFLINE_CUM_DEBIT_LIMIT
,'' AS CUST_TOT_TOD_ALWD_TIMES
,'' AS CUST_COMMU_CODE
,'' AS CARD_HOLDER
,'NRML' AS CUST_HLTH
,'' AS CUST_HLTH_CODE
,case when t1.AcType>='90' then 'Y' else 'N' end  AS TFPARTYFLAG	--need to map with the mapping sheet condition and value should be either Y or N
,t1.BranchCode AS PRIMARY_SOL_ID
,'' AS CONSTITUTION_REF_CODE
,'' AS CUST_OTHR_BANK_CODE
,'' AS CUST_FIRST_ACCT_DATE
,'' AS CHRG_LEVEL_CODE
,'' AS CHRG_DR_FORACID
,'' AS CHRG_DR_SOL_ID
,'N' AS CUST_CHRG_HISTORY_FLG
,'N' AS COMBINED_STMT_REQD
,'' AS LOANS_STMT_TYPE
,'' AS TD_STMT_TYPE
,'' AS COMB_STMT_CHRG_CODE
,'' AS DESPATCH_MODE
,'' AS CS_LAST_PRINTED_DATE
,'' AS CS_NEXT_DUE_DATE
,'N' AS ALLOW_SWEEPS
,'' AS PS_FREQ_TYPE
,'' AS PS_FREQ_WEEK_NUM
,'' AS PS_FREQ_WEEK_DAY
,'' AS PS_FREQ_START_DD
,'' AS PS_FREQ_HLDY_STAT
,'CUSTOMER' AS ENTITY_TYPE
,'' AS LINKEDRETAILCIF
,'N' AS HSHLDUFLAG
,'' AS SMALL_STR1
,'' AS SMALL_STR2
,'' AS SMALL_STR3
,'' AS SMALL_STR4
,'' AS SMALL_STR5
,'' AS SMALL_STR6
,'' AS SMALL_STR7
,'' AS SMALL_STR8
,'' AS SMALL_STR9
,'' AS SMALL_STR10
,'' AS MED_STR1
,'' AS MED_STR2
,'' AS MED_STR3
,'' AS MED_STR4
,'' AS MED_STR5
,'' AS MED_STR6
,'' AS MED_STR7
,'' AS MED_STR8
,'' AS MED_STR9
,'' AS MED_STR10
,'' AS LARGE_STR1
,'' AS LARGE_STR2
,'' AS LARGE_STR3
,'' AS LARGE_STR4
,'' AS LARGE_STR5
,'' AS DATE1
,'' AS DATE2
,'' AS DATE3
,'' AS DATE4
,'' AS DATE5
,'' AS DATE6
,'' AS DATE7
,'' AS DATE8
,'' AS DATE9
,'' AS DATE10
,'' AS NUMBER1
,'' AS NUMBER2
,'' AS NUMBER3
,'' AS NUMBER4
,'' AS NUMBER6
,'' AS NUMBER5
,'' AS NUMBER7
,'' AS NUMBER8
,'' AS NUMBER9
,'' AS NUMBER10
,'' AS DECIMAL1
,'' AS DECIMAL2
,'' AS DECIMAL3
,'' AS DECIMAL4
,'' AS DECIMAL5
,'' AS DECIMAL6
,'' AS DECIMAL7
,'' AS DECIMAL8
,'' AS DECIMAL9
,'' AS DECIMAL10
,'' AS CORE_CUST_ID  -- Need to be confirmed
,'' AS PERSONTYPE
,'INFENG' AS CUST_LANGUAGE
,'' AS CUST_STAFF_STATUS
,'' AS PHONE
,'' AS EXTENSION
,'' AS FAX
,'' AS FAX_HOME
,'' AS PHONE_HOME
,'' AS PHONE_HOME2
,'' AS PHONE_CELL
,'' AS EMAIL_HOME
,'' AS EMAIL_PALM
,'' AS EMAIL
,'' AS CITY
,'' AS PREFERREDCHANNELID
,'' AS CUSTOMERRELATIONSHIPNO
,'' AS RELATIONSHIPVALUE
,'' AS CATEGORY
,'' AS NUMBEROFPRODUCTS
,'' AS RELATIONSHIPMGRID
,'' AS RELATIONSHIPCREATEDBYID
,t2.WebAddress AS URL
,'' AS STATUS
,'' AS INDUSTRY
,'' AS PARENTORG
,'' AS COMPETITOR
,'' AS SICCODE
,'' AS CIN
,'' AS DESIGNATION
,'' AS ASSISTANT
,'' AS INTERNALSCORE
,'' AS CREDITBUREAUSCOREVALIDITY
,'' AS CREDITBUREAUSCORE
,'' AS CREDITBUREAUREQUESTDATE
,'' AS CREDITBUREAUDESCRIPTION
,'' AS MAIDENNAMEOFMOTHER
,'' AS ANNUALREVENUE
,'' AS REVENUEUNITS
,'' AS TICKERSYMBOL
,'N' AS AUTOAPPROVAL
,'N' AS FREEZEPRODUCTSALE
,'' AS RELATIONSHIPFIELD1
,'' AS RELATIONSHIPFIELD2
,'' AS RELATIONSHIPFIELD3
,'' AS DELINQUENCYFLG
,'' AS CUSTOMERNREFLG
,'' AS COMBINEDSTATEMENTFLG
,'' AS CUSTOMERTRADE
,'' AS PLACEOFBIRTH
,'' AS COUNTRYOFBIRTH
,'' AS PROOFOFAGEFLAG
,'' AS PROOFOFAGEDOCUMENT
,'' AS NAMESUFFIX
,'' AS MAIDENNAME
,'' AS CUSTOMERPROFITABILITY
,'' AS CURRENTCREXPOSURE
,'' AS TOTALCREXPOSURE
,'' AS POTENTIALCRLINE
,'' AS AVAILABLECRLIMIT
,'' AS CREDITSCOREREQUESTEDFLAG
,'' AS CREDITHISTORYREQUESTEDFLAG
,'' AS GROUPID
,'' AS FLG1
,'' AS FLG2
,'' AS FLG3
,'' AS ALERT1
,'' AS ALERT2
,'' AS ALERT3
,'' AS RELATIONSHIPOFFER1
,'' AS RELATIONSHIPOFFER2
,'' AS DTDATE1
,'' AS DTDATE2
,'' AS DTDATE3
,'' AS DTDATE4
,'' AS DTDATE5
,'' AS DTDATE6
,'' AS DTDATE7
,'' AS DTDATE8
,'' AS DTDATE9
,RIGHT(SPACE(20)+CAST('100' AS VARCHAR(20)),20) AS AMOUNT1  -- Default value will be given by the bank
,'' AS AMOUNT2
,'' AS AMOUNT3
,'' AS AMOUNT4
,'' AS AMOUNT5
,'' AS STRFIELD1
,'' AS STRFIELD2
,'' AS STRFIELD3
,'' AS STRFIELD4
,'' AS STRFIELD5
,'' AS STRFIELD6
,'' AS STRFIELD7
,'' AS STRFIELD8
,'' AS STRFIELD9
,'' AS STRFIELD10
,'' AS STRFIELD11
,'' AS STRFIELD12
,'N' AS STRFIELD13  -- As per agreement with Finacle team
,'' AS STRFIELD14  -- dependent on STRFIELD13
,'' AS STRFIELD15
,'' AS USERFLAG1
,'' AS USERFLAG2
,'' AS USERFLAG3
,'' AS USERFLAG4
,'' AS MLUSERFIELD1
,'' AS MLUSERFIELD2
,'' AS MLUSERFIELD3
,'' AS MLUSERFIELD4
,'' AS MLUSERFIELD5
,'' AS MLUSERFIELD6
,'' AS MLUSERFIELD7
,'' AS MLUSERFIELD8
,'' AS MLUSERFIELD9
,'' AS MLUSERFIELD10
,'' AS MLUSERFIELD11
,'' AS NOTES
,'' AS PRIORITYCODE
,'' AS CREATED_FROM
,'' AS CONSTITUTION_CODE
,'N' AS STRFIELD16  --default value 'N'
,'' AS STRFIELD17
,'' AS STRFIELD18
,'' AS STRFIELD19
,'' AS STRFIELD20
,'' AS STRFIELD21
,'' AS STRFIELD22
,'' AS AMOUNT6
,'' AS AMOUNT7
,'' AS AMOUNT8
,'' AS AMOUNT9
,'' AS AMOUNT10
,'' AS AMOUNT11
,'' AS AMOUNT12
,'' AS INTFIELD1
,'' AS INTFIELD2
,'' AS INTFIELD3
,'' AS INTFIELD4
,'' AS INTFIELD5
,'' AS NICK_NAME
,'' AS MOTHER_NAME
,'' AS FATHER_HUSBAND_NAME
,'' AS PREVIOUS_NAME
,'' AS LEAD_SOURCE
,'' AS RELATIONSHIP_TYPE
,'' AS RM_GROUP_ID
,'' AS RELATIONSHIP_LEVEL
,'' AS DSA_ID
,'' AS PHOTOGRAPH_ID
,'' AS SECURE_ID
,'' AS DELIQUENCYPERIOD
,'' AS ADDNAME1
,'' AS ADDNAME2
,'' AS ADDNAME3
,'' AS ADDNAME4
,'' AS ADDNAME5
,'' AS OLDENTITYCREATEDON
,'' AS OLDENTITYTYPE
,'' AS OLDENTITYID
,'Y' AS DOCUMENT_RECEIVED
,'' AS SUSPEND_NOTES
,'' AS SUSPEND_REASON
,'' AS BLACKLIST_NOTES
,'' AS BLACKLIST_REASON
,'' AS NEGATED_NOTES
,'' AS NEGATED_REASON
,'MIGR' AS SEGMENTATION_CLASS		-- Default value for BPD
,'' AS NAME
,'' AS MANAGEROPINION
,'' AS INTROD_STATUS
,'INFENG' AS NATIVELANGCODE
,'' AS MINORATTAINMAJORDATE
,'' AS NREBECOMINGORDDATE
,'' AS STARTDATE
,'' AS ADD1_FIRST_NAME
,'' AS ADD1_MIDDLE_NAME
,'' AS ADD1_LAST_NAME
,'' AS ADD2_FIRST_NAME
,'' AS ADD2_MIDDLE_NAME
,'' AS ADD2_LAST_NAME
,'' AS ADD3_FIRST_NAME
,'' AS ADD3_MIDDLE_NAME
,'' AS ADD3_LAST_NAME
,'' AS ADD4_FIRST_NAME
,'' AS ADD4_MIDDLE_NAME
,'' AS ADD4_LAST_NAME
,'' AS ADD5_FIRST_NAME
,'' AS ADD5_MIDDLE_NAME
,'' AS ADD5_LAST_NAME
,'' AS DUAL_FIRST_NAME
,'' AS DUAL_MIDDLE_NAME
,'' AS DUAL_LAST_NAME
,'' AS CUST_COMMUNITY
,'' AS CORE_INTROD_CUST_ID
,'' AS INTROD_SALUTATION_CODE
,'' AS TDS_CUST_ID
,t2.CitizenshipNo AS NAT_ID_CARD_NUM
,'' AS PSPRT_ISSUE_DATE
,t2.PassportCountry AS PSPRT_DET
,--t2.PassportExpiryDate AS PSPRT_EXP_DATE
REPLACE(REPLACE(CONVERT(VARCHAR,t2.PassportExpiryDate,106), ' ','-'), ',','') AS PSPRT_EXP_DATE
,'NPR' AS CRNCY_CODE
,'' AS PREF_CODE
,'' AS INTROD_STATUS_CODE
,'' AS NATIVELANGTITLE_CODE
,'' AS GROUPID_CODE
,(select top 1 sector from (select case when CustType in ('CA','UA','XB','NB') then 'FORRE'
when CustType in ('UB','CB') then 'FORNR'
when CustType in ('NA','XA') then 'NEPRE'
else 'MIGR' end sector from AcCustType where CustTypeCode = 'B')x) AS SECTOR		
,'' AS SUBSECTOR
,'' AS CUSTCREATIONMODE
,'' AS FIRST_PRODUCT_PROCESSOR
,'' AS INTERFACE_REFERENCE_ID
,--case when p.ReferenceNo not in (select t1.MainCode #FinalMaster) then 'NRML'
--when day((getdate()-p.DueDate))<=30 then 'PASS' 
--when (day((getdate()-p.DueDate))>30 and  day((getdate()-p.DueDate))<=90 )then 'WATCH'
--when (day((getdate()-p.DueDate))>90 and  day((getdate()-p.DueDate))<=180 )then 'SUBS'
--when (day((getdate()-p.DueDate))>180 and  day((getdate()-p.DueDate))<=365 )then 'DOUBT' 
--when day((getdate()-p.DueDate))>365 then 'LOSS' end 
'NRML' AS CUST_HEALTH_REF_CODE
,'' AS TDS_CIFID
,'' AS PREF_CODE_RCODE
,'' AS CUST_SWIFT_CODE_DESC
,'' AS IS_SWIFT_CODE_OF_BANK
,'' AS NATIVELANGCODE_CODE
,'' AS CREATEDBYSYSTEMID
,'COMMEML' AS PREFERREDEMAILTYPE
,'MOBILE' AS PREFERREDPHONE
,'' AS FIRST_NAME_NATIVE
,'' AS MIDDLE_NAME_NATIVE
,'' AS LAST_NAME_NATIVE
,'' AS SHORT_NAME_NATIVE
,'' AS FIRST_NAME_NATIVE1
,'' AS MIDDLE_NAME_NATIVE1
,'' AS LAST_NAME_NATIVE1
,'' AS SHORT_NAME_NATIVE1
,'' AS SECONDARYRM_ID
,'' AS TERTIARYRM_ID
,'MIGR' AS SUBSEGMENT			-- need to change as per BPD
,'' AS ACCESSOWNERGROUP
,'' AS ACCESSOWNERSEGMENT
,'' AS ACCESSOWNERBC
,'' AS ACCESSOWNERAGENT
,'' AS ACCESSASSIGNEEAGENT
,'' AS CHARGELEVELCODE
,'' AS INTUSERFIELD1
,'' AS INTUSERFIELD2
,'' AS INTUSERFIELD3
,'' AS INTUSERFIELD4
,'' AS INTUSERFIELD5
,'' AS STRUSERFIELD1
,'' AS STRUSERFIELD2
,'Y' AS STRUSERFIELD3
,'' AS STRUSERFIELD4
,'' AS STRUSERFIELD5
,'' AS STRUSERFIELD6
,'' AS STRUSERFIELD7
,'' AS STRUSERFIELD8
,'' AS STRUSERFIELD9
,'' AS STRUSERFIELD10
,'' AS STRUSERFIELD11
,'' AS STRUSERFIELD12
,'' AS STRUSERFIELD13
,'' AS STRUSERFIELD14
,'' AS STRUSERFIELD15
,'' AS STRUSERFIELD16
,'' AS STRUSERFIELD17
,'' AS STRUSERFIELD18
,'' AS STRUSERFIELD19
,'' AS STRUSERFIELD20
,'' AS STRUSERFIELD21
,'' AS STRUSERFIELD22
,'' AS STRUSERFIELD23
,'' AS STRUSERFIELD24
,t2.Remarks AS STRUSERFIELD25
,'' AS STRUSERFIELD26
,'' AS STRUSERFIELD27
,'' AS STRUSERFIELD28
,'' AS STRUSERFIELD29
,'' AS STRUSERFIELD30
,'' AS DATEUSERFIELD1
,'' AS DATEUSERFIELD2
,'' AS DATEUSERFIELD3
,'' AS DATEUSERFIELD4
,'' AS DATEUSERFIELD5
,'' AS BACKENDID
,'' AS RISK_PROFILE_SCORE
,'' AS RISK_PROFILE_EXPIRY_DATE
,'MOBILE' AS PREFERREDPHONETYPE
,t2.eMail AS PREFERREDEMAIL
,'' AS NOOFCREDITCARDS
,'' AS REASONFORMOVINGOUT
,'' AS COMPETITORPRODUCTID
,'' AS OCCUPATIONTYPE
,'01' AS BANK_ID
,'' AS ZAKAT_DEDUCTION
,'' AS ASSET_CLASSIFICATION
,'' AS CUSTOMER_LEVEL_PROVISIONING
,'' AS ISLAMIC_BANKING_CUSTOMER
,'GREGORIAN' AS PREFERREDCALENDAR
,'' AS IDTYPER1
,'' AS IDTYPER2
,'' AS IDTYPER3
,'' AS IDTYPER4
,'' AS IDTYPER5
,'' AS CUST_LAST_NAME_ALT1
,'' AS CUST_FIRST_NAME_ALT1
,'' AS CUST_MIDDLE_NAME_ALT1
,'' AS STRFIELD6_ALT1
,'' AS NAME_ALT1
,'' AS SHORT_NAME_ALT1
,CASE WHEN t1.ClientCode = tempcust.ClientCode THEN 'Y'
ELSE 'N' 
END AS ISEBANKINGENABLED
,'N' AS PURGEFLAG
,CASE WHEN t2.ClientStatus = 'Z' THEN 'Y'
WHEN t2.ClientStatus IS NULL OR t2.ClientStatus = '' THEN 'N'
ELSE 'N' END AS SUSPENDED
,CASE WHEN t2.ClientStatus = 'b' THEN 'Y'
WHEN t2.ClientStatus IS NULL OR t2.ClientStatus = '' THEN 'N'
ELSE 'N' END AS BLACKLISTED
,'' AS NEGATED
,'' AS ACCOUNTID
,t2.Address1 AS ADDRESS_LINE1
,t2.Address2 AS ADDRESS_LINE2
,t2.Address3 AS ADDRESS_LINE3
,'' AS STATE
,CASE WHEN ct.ISOCode = 'GB' THEN 'UK' ELSE ct.ISOCode END AS COUNTRY
,'' AS ZIP
,'' AS BOCREATEDBYLOGINID
,'' AS SUBMITFORKYC
,replace(replace(convert(varchar,t2.Review_Date,106),' ','-'),',','') AS KYC_REVIEWDATE
,'' AS KYC_DATE
,CASE WHEN lower(t2.Key_Risk_Grade ) like 'l%' THEN 'LOW'
WHEN lower(t2.Key_Risk_Grade ) LIKE 'm%' THEN 'MODERATE'
WHEN lower(t2.Key_Risk_Grade) LIKE 'h%' THEN 'HIGH'
ELSE 'MIGR' END AS RISKRATING
,CASE WHEN t1.AcType = '0B' THEN 'Y' ELSE 'N' END AS SENIORCITIZEN
,'' AS SENCITIZENAPPLICABLEDATE
,'' AS SENCITIZENCONVERSIONFLAG
,'' AS FOREIGNACCTAXREPORTINGREQ
,'' AS FOREIGNTAXREPORTINGCOUNTRY
,'' AS FOREIGNTAXREPORTINGSTATUS
,'' AS LASTFOREIGNTAXREVIEWDATE
,'' AS NEXTFOREIGNTAXREVIEWDATE
,'' AS FATCAREMARKS
,'' AS DATEOFDEATH
,'' AS DATEOFNOTIFICATION
,'' AS PHYSICAL_STATE
,'' AS UNIQUEIDNUMBER
FROM #FinalMaster t1
JOIN ClientTable t2 ON t1.ClientCode = t2.ClientCode
JOIN #ClientName CName ON CName.ClientCode = t2.ClientCode
LEFT JOIN CountryTable ct on ct.CyCode = t1.CyCode
LEFT JOIN FinacleEmployeeTable fe on fe.ClientCode = t2.ClientCode
LEFT JOIN PastDuedList p on p.ReferenceNo = t1.MainCode
LEFT JOIN AcCustType t4 ON t1.BranchCode = t4.BranchCode and t1.MainCode = t4.MainCode AND t4.CustType = 'B' -- need to be checked with bank data putting inner join
LEFT JOIN 
(
	SELECT ClientCode FROM Master t1 JOIN CustomerTable t2 ON t1.MainCode = t2.MainCode0
) AS tempcust ON t1.ClientCode = tempcust.ClientCode  -- Logic for connection between CustomerTable and Master as defined in logic to reduce complexity
LEFT JOIN
(
	SELECT t1.ClientCode,
	CASE WHEN ((UPPER(t1.Name) LIKE UPPER('%MINOR%')) OR (t2.Gender='m') OR (t1.ClientCode IN (SELECT ClientCode FROM #FinalMaster WHERE AcType IN('OM','OH','OI'))) OR t2.MaritalStatus='N') THEN 'Y' 
	ELSE 'N'
	END AS CUSTOMERMINOR
	FROM #FinalMaster t1 LEFT JOIN ClientTable t2 ON t1.ClientCode = t2.ClientCode
) AS tminor ON t1.ClientCode = tminor.ClientCode   -- logic added for minor account in join to pass to multiple column conditions
,ControlTable ctrlt
WHERE LEFT(t2.ClientCode,1) <> '_'
AND EXISTS
(
	SELECT 1 FROM AcCustType WHERE MainCode = t1.MainCode and CustTypeCode = 'Z' and CustType IN ('11','12')
) 
) AS dt 
--ORDER BY 1