-- TOTAL Record = 4538
select 
  'G' Func_Code
, NULL Bill_Param_Type
, cm.ClientCode CIF_ID 		--need to put CO or not?
, lc.CyCodeLc CCY
, 'Y' underDC
, ld.BranchCode solId
, ld.ParentReferenceNo billId
, NULL discAmt
, NULL otherDeduction
, ld.BaseAmount billAmt
, case when cm.AcType = '90' then 'S'
  when cm.AcType = '9F' then 'U' end billTenor
, ld.EnteredOn lodgeDate
, 'NP' billCountry
, isnull (NegoRefNo , 'MIGRATION_DATA') otherBanksRefNo
, cm.Name partyName
, cm.Address1 address1
, cm.Address2 address2
, NULL invoiceAmt
, NULL invoiceCrncy
, NULL CBbank
, NULL CBbranch
, 'SRBLNPKAXXX' BCbicId
, 'L' dueDateInd
, ld.DocNegoDate billDate
, ld.DueOn dueDate
, ld.DocShipDate onBoardDate
, ld.ParentReferenceNo DCno
, lc.NomAc foracid
, lc.NomAc oppChrgAccId
, lc.NomAc custLiabAcctId
, NULL advAmtPaid
, NULL refDate
, NULL paysysId
, NULL partyCIF_ID
, NULL Daddress3
, NULL Dcity
, NULL Dstate
, NULL Dcntry
, NULL Dpostalcode
, NULL DBbank
, NULL DBbranch
, NULL DBName
, NULL DBaddress1
, NULL DBaddress2
, NULL DBaddress3
, NULL DBcity
, NULL DBstate
, NULL DBcntry
, NULL DBpostalcode
, NULL DBbicId
, NULL DBpartyId
, NULL DBaddrType
, NULL CBName
, NULL CBaddress1
, NULL CBaddress2
, NULL CBaddress3
, NULL CBcity
, NULL CBstate
, NULL CBcntry
, NULL CBpostalcode
, NULL CBbicId
, NULL CBpartyId
, NULL CBaddrType
, NULL COBbank
, NULL COBbranch
, NULL COBName
, NULL COBaddress1
, NULL COBaddress2
, NULL COBaddress3
, NULL COBcity
, NULL COBstate
, NULL COBcntry
, NULL COBpostalcode
, NULL COBbicId
, NULL COBpartyId
, NULL COBaddrType
, NULL RBbank
, NULL RBbranch
, NULL RBName
, NULL RBaddress1
, NULL RBaddress2
, NULL RBaddress3
, NULL RBcity
, NULL RBstate
, NULL RBcntry
, NULL RBpostalcode
, NULL RBbicId
, NULL RBpartyId
, NULL RBaddrType
, NULL CABbank
, NULL CABbranch
, NULL CABName
, NULL CABaddress1
, NULL CABaddress2
, NULL CABaddress3
, NULL CABcity
, NULL CABstate
, NULL CABcntry
, NULL CABpostalcode
, NULL CABbicId
, NULL CABpartyId
, NULL CABaddrType
, NULL draftNo
, NULL fixedTransitPeriod
, NULL gracePeriod
, NULL docsRcvdOn
, NULL acceptDate
, NULL tenorMonth
, NULL tenorDay
, NULL dcUtilAmt
, NULL shpGrntOrdNo1
, NULL shpGrntOrdNo2
, NULL shpGrntOrdNo3
, NULL shpGrntOrdNo4
, NULL shpGrntOrdNo5
, NULL othrBankPrftAmt
, NULL carrierCode
, NULL originOfGoods
, NULL portOfDest
, NULL consigneeCntry
, NULL shpmtTerms
, NULL commCode
, NULL docRcvdFlg
, NULL docStatus
, NULL solId1
, NULL ordNo1
, NULL solId2
, NULL ordNo2
, NULL solId3
, NULL ordNo3
, NULL solId4
, NULL ordNo4
, NULL solId5
, NULL ordNo5
, NULL expOrdNo
, NULL licenseDate
, NULL insurPcnt
, NULL insurAmt
, NULL insuredBy
, NULL policyNo
, NULL policyDate
, NULL insurCompName
, NULL payableAt
, NULL premiumCcy
, NULL premiumAmt
, NULL insurConvRateCode
, NULL insurConvRate
, NULL insurAddrLine1
, NULL insurAddrLine2
, NULL insurAddrLine3
, NULL insurCity
, NULL insurState
, NULL insurCntry
, NULL insurPostalCode
, NULL insurExpDate
, NULL invoiceNo
, NULL invoiceDate
, NULL underReserve
, NULL intermTrade
, NULL purposeBill
, NULL regApprovalNo
, NULL ourCommAmt
, NULL ourPTAmt
, NULL purchaseAcctId
, NULL lcndaAcctId
, NULL goodsInTranAcctId
, NULL purchaseAmt
, NULL payableAcctId
, NULL prfxMurabhaLmtId
, NULL sfxMurabhaLmtId
, NULL prftTableCode
, NULL promPurRcvd
, NULL promPurDate
, NULL promPurRefNo
, NULL purAcceptAdvice
, NULL exeAdvNo1
, NULL exeAdvNo2
, NULL exeAdvNo3
, NULL exeAdvNo4
, NULL exeAdvNo5
, NULL invAcctId
, NULL goodsPurThirdParty
, NULL islamicRateCode
, NULL islamicRate
, NULL capitalTran
, NULL intendToExport
, NULL inwardDcRefNum
from LcMaster lc
left join LcDocArrived ld on ld.ParentReferenceNo = lc.ReferenceNo and ld.CyCodeLc = lc.CyCodeLc and ld.BranchCode = lc.BranchCode
left join (select m.MainCode , m.Name , m.ClientCode , m.BranchCode , m.AcType , c.Address1 , c.Address2 
from Master m , ClientTable c where m.ClientCode = c.ClientCode) cm on cm.MainCode = lc.MainCode 


 
