-- SQL Code for IDCUPL

SELECT
'A' 									AS Func_Code
,dm.BranchCode 							AS Sol_Id
,dm.ReferenceNo 						AS DC_Num
,'' 									AS Event_Amount
,CONVERT(VARCHAR(10),dm.IssueDate,105) 	AS Event_Date
,dm.BaseAmount 							AS DC_Type
,curt.CyDesc 							AS DC_Currency_Cif_Id
,'' 									AS DC_Cif_Id
,dm.Applicant1 							AS DC_Party_Name  -- Need to confirm with bank as some logic is provided
,dm.Applicant2 							AS DC_Party_Address_1
,dm.Applicant3 							AS DC_Party_Address_2
,'' 									AS DC_Party_Address_3
,'' 									AS DC_Party_City
,'' 									AS DC_Party_State
,'' 									AS DC_Party_Country
,'' 									AS Postal_Code
,dm.Nominee 							AS DC_Account_Id
,dm.ReferenceNo 						AS Applicant_Refernce_Num
,'' 									AS Tolerance_Limit
,'' 									AS Negative_Tolerance_pcnt
,'MID' 									AS DC_Rate_Code
,dm.CyRate 								AS DC_Rate
,'' 									AS DC_Advance_Amount
,'' 									AS DC_Interest_pcnt
,'' 									AS DC_Additional_Amt
,'' 									AS DC_Interest_Remarks
,'' 									AS DC_Max_Credit_
,'' 									AS DC_Purchase_Order_No
,'' 									AS DC_Pord_Date
,'' 									AS DC_Purchase_Order_Last_Amend_Date
,'' 									AS DC_Total_Num_of_Amendments
,'' 									AS Pre_Advice_Flag
,'' 									AS Pre_Advice_Date
,'' 									AS Pre_Advice_Ref_Num
,'' 									AS Other_Bank_Ref_Num
,'' 									AS DC_Paysys_Id
,ct.ClientCode 							AS DC_Beneficiary_Cif_Id
,dm.Beneficiary1 						AS DC_Beneficiary_Name
,dm.Beneficiary2 						AS DC_Beneficiary_Address1
,dm.Beneficiary3 						AS DC_Beneficiary_Address2
,'' 									AS DC_Beneficiary_Address3
,'' 									AS DC_Beneficiary_City
,'' 									AS DC_Beneficiary_State
,'' 									AS DC_Beneficiary_Country
,'' 									AS DC_Beneficiary_PinCode
,'' 									AS DC_Applicant_Branch
,dm.IssueBankName 						AS DC_Applicant_Bank  -- Need to confirm with bank as the size increases beyond the given limit
,dm.IssueBankName 						AS DC_Applicant_Bank_Name
,dm.IssueBankAdd1 						AS DC_Applicant_Bank_Address1
,dm.IssueBankAdd2 						AS DC_Applicant_Bank_Address2
,dm.IssueBankAdd3 						AS DC_Applicant_Bank_Address3
,'' 									AS DC_Applicant_Bank_City
,'' 									AS DC_Applicant_Bank_State
,'' 									AS DC_Applicant_Bank_Country
,'' 									AS DC_Applicant_Bank_PinCode
,'' 									AS DC_Applicant_Bic_Code
,'' 									AS DC_Party_Identifier
,'' 									AS DC_Applicant_Bank_Address_Type
,'' 									AS DC_Issuing_Branch
,'' 									AS DC_Issuing_Bank
,'' 									AS DC_Issuing_Name
,'' 									AS DC_Issuing_Address_1
,'' 									AS DC_Issuing_Address_2
,'' 									AS DC_Issuing_Address_3
,'' 									AS DC_Issuing_City
,'' 									AS DC_Issuing_State
,'' 									AS DC_Issuing_Country
,'' 									AS DC_Issuing_Pin_Code
,'' 									AS DC_Issue_Bic_Code
,'' 									AS DC_Issue_Party_ID
,'' 									AS DC_Issue_Ref_No
,'' 									AS DC_Issue_Address_Type
,'' 									AS DC_Advising_Branch_Code
,'' 									AS DC_Advising_Bank_Code
,'SANIMA BANK LIMITED' 					AS DC_Advising_Name
,'' 									AS DC_Advising_Address_1
,'' 									AS DC_Advising_Address_2
,'' 									AS DC_Advising_Address_3
,'' 									AS DC_Advising_City
,'' 									AS DC_Advising_State
,'' 									AS DC_Advising_Country
,'' 									AS DC_Advising_Pin_Code
,'' 									AS DC_Advising_Bic_Code
,'' 									AS DC_Advising_Party_Id
,'' 									AS DC_Advising_Address_Type
,'' 									AS DC_Drawee_Branch
,'' 									AS DC_Drawee_Bank
,'' 									AS DC_Drawee_Name
,'' 									AS DC_Drawee_Address_1
,'' 									AS DC_Drawee_Address_2
,'' 									AS DC_Drawee_Address_3
,'' 									AS DC_Drawee_City
,'' 									AS DC_Drawee_State
,'' 									AS DC_Drawee_Country
,'' 									AS DC_Drawee_Pin_Code
,'' 									AS DC_Drawee_BIC_Code
,'' 									AS DC_Drawee_Party_Id
,'' 									AS DC_Drawee_Address_Type
,'' 									AS DC_Available_with_Branch
,'' 									AS DC_Available_with_Bank
,'' 									AS DC_Available_with_Name
,'' 									AS DC_Available_with_Address_1
,'' 									AS DC_Available_with_Address_2
,'' 									AS DC_Available_with_Address_3
,'' 									AS DC_Available_with_City
,'' 									AS DC_Available_with_State
,'' 									AS DC_Available_with_Country
,'' 									AS DC_Available_with_Pin_Code
,'' 									AS DC_Available_with_BIC_Code
,'' 									AS DC_Available_with_Party_Id
,'' 									AS DC_Available_by
,'' 									AS DC_Available_with_Address_Type
,'' 									AS DC_Reimbursing_Branch
,'' 									AS DC_Reimbursing_Bank
,'' 									AS DC_Reimbursing_Name
,'' 									AS DC_Reimbursing_Address_1
,'' 									AS DC_Reimbursing_Address_2
,'' 									AS DC_Reimbursing_Address_3
,'' 									AS DC_Reimbursing_City
,'' 									AS DC_Reimbursing_State
,'' 									AS DC_Reimbursing_Country
,'' 									AS DC_Reimbursing_Pin_Code
,'' 									AS DC_Reimbursing_BIC_Code
,'' 									AS DC_Reimbursing_Party_Id
,'' 									AS DC_Reimbursing_Address_Type
,'' 									AS DC_Advise_through_Branch
,'' 									AS DC_Advise_through_Bank
,'' 									AS DC_Advise_through_Name
,'' 									AS DC_Advise_through_Address_1
,'' 									AS DC_Advise_through_Address_2
,'' 									AS DC_Advise_through_Address_3
,'' 									AS DC_Advise_through_City
,'' 									AS DC_Advise_through_State
,'' 									AS DC_Advise_through_Country
,'' 									AS DC_Advise_through_Pin_Code
,'' 									AS DC_Advise_through_BIC_Code
,'' 									AS DC_Advise_through_Party_Id
,'' 									AS DC_Advise_through_Location
,'' 									AS DC_Advise_through_Address_Type
,'' 									AS Partial_Shipment_Flag
,'' 									AS Trans_Shipment_Flag
,'' 									AS Last_Shipment_Date
,'' 									AS DC_Negotiation_Period
,'' 									AS Shipment_Mode
,'' 									AS Shipment_Term
,'' 									AS Despatch_origin_port_code
,'' 									AS Despatch_destination_port_code
,'' 									AS Port_of_Origin
,'' 									AS Port_of_Destination
,'' 									AS House_Air_Bill_Flag
,'' 									AS Shipment_Desc
,'' 									AS Agent_code
,'' 									AS Commodity_code
,'' 									AS Origin_of_Goods
,'' 									AS License_Code
,'' 									AS Insurance_Pcnt
,'' 									AS Insured_Amount
,'' 									AS Insured_By
,'' 									AS Policy_Num
,'' 									AS Policy_Date
,'' 									AS Insured_Company
,'' 									AS Payable_At
,'' 									AS Premium_Amt
,'' 									AS DC_Reimbursement_Msg_Flag
,'' 									AS DC_Reimbursemnet_Applicable_Rules
,'' 									AS Nostro_Acct_Num
,'' 									AS DC_Charges_Borne_By
,'N' 									AS DC_Confirmation_Instructions
,'N' 									AS DC_Confirmation_Required_By
,'' 									AS DC_Agent_Commision_pcnt
,'' 									AS Capital_adequecy_code
,'2' 									AS Revocable_Flag
,'Y' 									AS DC_Irrevocable_Flag
,'' 									AS DC_Transferrable_Flag
,'' 									AS DC_stanby_mode_flag
,'' 									AS DC_Revolving_Flag
,'' 									AS DC_Back_to_Back_Flag
,m.AcType 								AS Defferred_DC_flag   -- Need to confirm with bank as the size of value increases beyond given size
,'N'									AS Red_Clause_DC_flag
,'' 									AS Reinstatement_Type
,'' 									AS DC_Reinstatement_Day
,'' 									AS Max_Reinstatements
,'' 									AS Reinstated_By_Amount
,'' 									AS Reinstatement_Remarks
,'' 									AS DC_Back_to_Back_Ref_Num
,'UCP LATEST VERSION' 					AS DC_Applicable_Rule
,'' 									AS DC_Applicable_Sub_Rule
,'' 									AS DC_Tenor
,CONVERT(VARCHAR(10),dm.ExpiryDate,105) AS DC_expiry_Date
,'' 									AS DC_Place_of_Expiry
,'' 									AS LimitPrefix
,'' 									AS Limit_Suffix
,'' 									AS Limit_Margin_Pcnt
,'' 									AS Internal_Limits
,'' 									AS Amendment_Indicator
,'' 									AS Amendment_Status
,'' 									AS Amendment_Remarks
,'' 									AS Add_Confirmation
,'' 									AS DC_Confirmation_Amount
,'' 									AS DC_Confirmation_Pcnt
,'' 									AS Usance_Period
,'' 									AS Amend_Tenor_Details
,'' 									AS Purchase_Order_Sol_Id_1
,'' 									AS Purchase_Order_Number_1
,'' 									AS Purchase_Order_Sol_Id_2
,'' 									AS Purchase_Order_Number_2
,'' 									AS Purchase_Order_Sol_Id_3
,'' 									AS Purchase_Order_Number_3
,'' 									AS Purchase_Order_Sol_Id_4
,'' 									AS Purchase_Order_Number_4
,'' 									AS Purchase_Order_Sol_Id_5
,'' 									AS Purchase_Order_Number_5
,dm.Nominee 							AS Beneficiary_Account_Id
,'' 									AS Insurance_Address_Line_1
,'' 									AS Insurance_Address_Line_2
,'' 									AS Insurance_Address_Line_3
,'' 									AS Insurance_City
,'' 									AS Insurance_State
,'' 									AS Insurance_Country
,'' 									AS Insurance_Pin_Code
,'' 									AS Insurance_Expiry_Date
,'' 									AS remitRecvdThrough
,'' 									AS recvdRemitId
,'' 									AS recvdPaymentDate
,'' 									AS recvdAdvRemarks
,'' 									AS capitalGoodsTran
FROM DnMaster dm
JOIN Master m ON dm.MainCode = m.MainCode AND dm.BranchCode = m.BranchCode
LEFT JOIN ClientTable ct ON m.ClientCode = ct.ClientCode
LEFT JOIN CurrencyTable curt ON m.CyCode = curt.CyCode 
where m.IsBlocked NOT IN ('C','o')
and left(m.ClientCode,1) <> '_'
and len(m.MainCode) >= 8
AND EXISTS
(
	SELECT 1 FROM AcCustType WHERE MainCode = m.MainCode and CustTypeCode = 'Z' and CustType IN ('11','12')
)

UNION

-- SQL Code for IDCUPL

SELECT
'A' 									AS Func_Code
,dm.BranchCode 							AS Sol_Id
,dm.ReferenceNo 						AS DC_Num
,'' 									AS Event_Amount
,CONVERT(VARCHAR(10),dm.IssueDate,105) 	AS Event_Date
,dm.BaseAmount 							AS DC_Type
,curt.CyDesc 							AS DC_Currency_Cif_Id
,'' 									AS DC_Cif_Id
,dm.Applicant1 							AS DC_Party_Name  -- Need to confirm with bank as some logic is provided
,dm.Applicant2 							AS DC_Party_Address_1
,dm.Applicant3 							AS DC_Party_Address_2
,'' 									AS DC_Party_Address_3
,'' 									AS DC_Party_City
,'' 									AS DC_Party_State
,'' 									AS DC_Party_Country
,'' 									AS Postal_Code
,dm.Nominee 							AS DC_Account_Id
,dm.ReferenceNo 						AS Applicant_Refernce_Num
,'' 									AS Tolerance_Limit
,'' 									AS Negative_Tolerance_pcnt
,'MID' 									AS DC_Rate_Code
,dm.CyRate 								AS DC_Rate
,'' 									AS DC_Advance_Amount
,'' 									AS DC_Interest_pcnt
,'' 									AS DC_Additional_Amt
,'' 									AS DC_Interest_Remarks
,'' 									AS DC_Max_Credit_
,'' 									AS DC_Purchase_Order_No
,'' 									AS DC_Pord_Date
,'' 									AS DC_Purchase_Order_Last_Amend_Date
,'' 									AS DC_Total_Num_of_Amendments
,'' 									AS Pre_Advice_Flag
,'' 									AS Pre_Advice_Date
,'' 									AS Pre_Advice_Ref_Num
,'' 									AS Other_Bank_Ref_Num
,'' 									AS DC_Paysys_Id
,ct.ClientCode 							AS DC_Beneficiary_Cif_Id
,dm.Beneficiary1 						AS DC_Beneficiary_Name
,dm.Beneficiary2 						AS DC_Beneficiary_Address1
,dm.Beneficiary3 						AS DC_Beneficiary_Address2
,'' 									AS DC_Beneficiary_Address3
,'' 									AS DC_Beneficiary_City
,'' 									AS DC_Beneficiary_State
,'' 									AS DC_Beneficiary_Country
,'' 									AS DC_Beneficiary_PinCode
,'' 									AS DC_Applicant_Branch
,dm.IssueBankName 						AS DC_Applicant_Bank  -- Need to confirm with bank as the size increases beyond the given limit
,dm.IssueBankName 						AS DC_Applicant_Bank_Name
,dm.IssueBankAdd1 						AS DC_Applicant_Bank_Address1
,dm.IssueBankAdd2 						AS DC_Applicant_Bank_Address2
,dm.IssueBankAdd3 						AS DC_Applicant_Bank_Address3
,'' 									AS DC_Applicant_Bank_City
,'' 									AS DC_Applicant_Bank_State
,'' 									AS DC_Applicant_Bank_Country
,'' 									AS DC_Applicant_Bank_PinCode
,'' 									AS DC_Applicant_Bic_Code
,'' 									AS DC_Party_Identifier
,'' 									AS DC_Applicant_Bank_Address_Type
,'' 									AS DC_Issuing_Branch
,'' 									AS DC_Issuing_Bank
,'' 									AS DC_Issuing_Name
,'' 									AS DC_Issuing_Address_1
,'' 									AS DC_Issuing_Address_2
,'' 									AS DC_Issuing_Address_3
,'' 									AS DC_Issuing_City
,'' 									AS DC_Issuing_State
,'' 									AS DC_Issuing_Country
,'' 									AS DC_Issuing_Pin_Code
,'' 									AS DC_Issue_Bic_Code
,'' 									AS DC_Issue_Party_ID
,'' 									AS DC_Issue_Ref_No
,'' 									AS DC_Issue_Address_Type
,'' 									AS DC_Advising_Branch_Code
,'' 									AS DC_Advising_Bank_Code
,'SANIMA BANK LIMITED' 					AS DC_Advising_Name
,'' 									AS DC_Advising_Address_1
,'' 									AS DC_Advising_Address_2
,'' 									AS DC_Advising_Address_3
,'' 									AS DC_Advising_City
,'' 									AS DC_Advising_State
,'' 									AS DC_Advising_Country
,'' 									AS DC_Advising_Pin_Code
,'' 									AS DC_Advising_Bic_Code
,'' 									AS DC_Advising_Party_Id
,'' 									AS DC_Advising_Address_Type
,'' 									AS DC_Drawee_Branch
,'' 									AS DC_Drawee_Bank
,'' 									AS DC_Drawee_Name
,'' 									AS DC_Drawee_Address_1
,'' 									AS DC_Drawee_Address_2
,'' 									AS DC_Drawee_Address_3
,'' 									AS DC_Drawee_City
,'' 									AS DC_Drawee_State
,'' 									AS DC_Drawee_Country
,'' 									AS DC_Drawee_Pin_Code
,'' 									AS DC_Drawee_BIC_Code
,'' 									AS DC_Drawee_Party_Id
,'' 									AS DC_Drawee_Address_Type
,'' 									AS DC_Available_with_Branch
,'' 									AS DC_Available_with_Bank
,'' 									AS DC_Available_with_Name
,'' 									AS DC_Available_with_Address_1
,'' 									AS DC_Available_with_Address_2
,'' 									AS DC_Available_with_Address_3
,'' 									AS DC_Available_with_City
,'' 									AS DC_Available_with_State
,'' 									AS DC_Available_with_Country
,'' 									AS DC_Available_with_Pin_Code
,'' 									AS DC_Available_with_BIC_Code
,'' 									AS DC_Available_with_Party_Id
,'' 									AS DC_Available_by
,'' 									AS DC_Available_with_Address_Type
,'' 									AS DC_Reimbursing_Branch
,'' 									AS DC_Reimbursing_Bank
,'' 									AS DC_Reimbursing_Name
,'' 									AS DC_Reimbursing_Address_1
,'' 									AS DC_Reimbursing_Address_2
,'' 									AS DC_Reimbursing_Address_3
,'' 									AS DC_Reimbursing_City
,'' 									AS DC_Reimbursing_State
,'' 									AS DC_Reimbursing_Country
,'' 									AS DC_Reimbursing_Pin_Code
,'' 									AS DC_Reimbursing_BIC_Code
,'' 									AS DC_Reimbursing_Party_Id
,'' 									AS DC_Reimbursing_Address_Type
,'' 									AS DC_Advise_through_Branch
,'' 									AS DC_Advise_through_Bank
,'' 									AS DC_Advise_through_Name
,'' 									AS DC_Advise_through_Address_1
,'' 									AS DC_Advise_through_Address_2
,'' 									AS DC_Advise_through_Address_3
,'' 									AS DC_Advise_through_City
,'' 									AS DC_Advise_through_State
,'' 									AS DC_Advise_through_Country
,'' 									AS DC_Advise_through_Pin_Code
,'' 									AS DC_Advise_through_BIC_Code
,'' 									AS DC_Advise_through_Party_Id
,'' 									AS DC_Advise_through_Location
,'' 									AS DC_Advise_through_Address_Type
,'' 									AS Partial_Shipment_Flag
,'' 									AS Trans_Shipment_Flag
,'' 									AS Last_Shipment_Date
,'' 									AS DC_Negotiation_Period
,'' 									AS Shipment_Mode
,'' 									AS Shipment_Term
,'' 									AS Despatch_origin_port_code
,'' 									AS Despatch_destination_port_code
,'' 									AS Port_of_Origin
,'' 									AS Port_of_Destination
,'' 									AS House_Air_Bill_Flag
,'' 									AS Shipment_Desc
,'' 									AS Agent_code
,'' 									AS Commodity_code
,'' 									AS Origin_of_Goods
,'' 									AS License_Code
,'' 									AS Insurance_Pcnt
,'' 									AS Insured_Amount
,'' 									AS Insured_By
,'' 									AS Policy_Num
,'' 									AS Policy_Date
,'' 									AS Insured_Company
,'' 									AS Payable_At
,'' 									AS Premium_Amt
,'' 									AS DC_Reimbursement_Msg_Flag
,'' 									AS DC_Reimbursemnet_Applicable_Rules
,'' 									AS Nostro_Acct_Num
,'' 									AS DC_Charges_Borne_By
,'N' 									AS DC_Confirmation_Instructions
,'N' 									AS DC_Confirmation_Required_By
,'' 									AS DC_Agent_Commision_pcnt
,'' 									AS Capital_adequecy_code
,'2' 									AS Revocable_Flag
,'Y' 									AS DC_Irrevocable_Flag
,'' 									AS DC_Transferrable_Flag
,'' 									AS DC_stanby_mode_flag
,'' 									AS DC_Revolving_Flag
,'' 									AS DC_Back_to_Back_Flag
,m.AcType 								AS Defferred_DC_flag   -- Need to confirm with bank as the size of value increases beyond given size
,'N'									AS Red_Clause_DC_flag
,'' 									AS Reinstatement_Type
,'' 									AS DC_Reinstatement_Day
,'' 									AS Max_Reinstatements
,'' 									AS Reinstated_By_Amount
,'' 									AS Reinstatement_Remarks
,'' 									AS DC_Back_to_Back_Ref_Num
,'UCP LATEST VERSION' 					AS DC_Applicable_Rule
,'' 									AS DC_Applicable_Sub_Rule
,'' 									AS DC_Tenor
,CONVERT(VARCHAR(10),dm.ExpiryDate,105) AS DC_expiry_Date
,'' 									AS DC_Place_of_Expiry
,'' 									AS LimitPrefix
,'' 									AS Limit_Suffix
,'' 									AS Limit_Margin_Pcnt
,'' 									AS Internal_Limits
,'' 									AS Amendment_Indicator
,'' 									AS Amendment_Status
,'' 									AS Amendment_Remarks
,'' 									AS Add_Confirmation
,'' 									AS DC_Confirmation_Amount
,'' 									AS DC_Confirmation_Pcnt
,'' 									AS Usance_Period
,'' 									AS Amend_Tenor_Details
,'' 									AS Purchase_Order_Sol_Id_1
,'' 									AS Purchase_Order_Number_1
,'' 									AS Purchase_Order_Sol_Id_2
,'' 									AS Purchase_Order_Number_2
,'' 									AS Purchase_Order_Sol_Id_3
,'' 									AS Purchase_Order_Number_3
,'' 									AS Purchase_Order_Sol_Id_4
,'' 									AS Purchase_Order_Number_4
,'' 									AS Purchase_Order_Sol_Id_5
,'' 									AS Purchase_Order_Number_5
,dm.Nominee 							AS Beneficiary_Account_Id
,'' 									AS Insurance_Address_Line_1
,'' 									AS Insurance_Address_Line_2
,'' 									AS Insurance_Address_Line_3
,'' 									AS Insurance_City
,'' 									AS Insurance_State
,'' 									AS Insurance_Country
,'' 									AS Insurance_Pin_Code
,'' 									AS Insurance_Expiry_Date
,'' 									AS remitRecvdThrough
,'' 									AS recvdRemitId
,'' 									AS recvdPaymentDate
,'' 									AS recvdAdvRemarks
,'' 									AS capitalGoodsTran
FROM DnMaster dm
JOIN Master m ON dm.MainCode = m.MainCode AND dm.BranchCode = m.BranchCode
LEFT JOIN ClientTable ct ON m.ClientCode = ct.ClientCode
LEFT JOIN CurrencyTable curt ON m.CyCode = curt.CyCode 
where m.IsBlocked NOT IN ('C','o')
and left(m.ClientCode,1) <> '_'
and len(m.MainCode) >= 8
AND EXISTS
(
	SELECT 1 FROM AcCustType WHERE MainCode = m.MainCode and CustTypeCode = 'Z' and CustType NOT IN ('11','12')
)