select
MainCode foracid												,
case when AcType = '0V' then 'W' else 'N' end  wtax_flg     ,	
case when AcType = '0V' then 'P' else ' ' end wtax_amount_scope_flg    ,		
case when TaxPostFrq=9 or IntPostFrqCr=9
or AcType in ('01','02','03','04','28','0X') then RIGHT(SPACE(8)+CAST('0' AS VARCHAR(8)),8)
else 	RIGHT(SPACE(8)+CAST('5' AS VARCHAR(8)),8) end wtax_pcnt                     ,		
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17)	wtax_floor_limit                                       ,
case when MainCode in 
(select MainCode from AcCustType where CustTypeCode='Z' and CustType in ('11','12')) then 'R0'+ ClientCode
when MainCode in 
(select MainCode from AcCustType where CustTypeCode='Z' and CustType not in ('11','12')) then 'C0'+ClientCode 
else 'N0'+ClientCode end CIF_id                       ,	--need to check case return result correctly
RIGHT(SPACE(10)+CAST('0' AS VARCHAR(10)),10) cust_cr_pref_pcnt                                      ,
RIGHT(SPACE(10)+CAST('0' AS VARCHAR(10)),10) cust_dr_pref_pcnt                                      ,
(select isnull((RIGHT(SPACE(10)+CAST(P.IntCrRateDef-M.IntCrRate AS VARCHAR(10)),10)),RIGHT(SPACE(10)+CAST('0' AS VARCHAR(10)),10)) from Master M, ParaTable P 
where M.BranchCode=P.BranchCode and M.AcType=P.AcType and M.CyCode=P.CyCode
and M.MainCode = Master.MainCode) id_cr_pref_pcnt                                        ,
(select isnull((RIGHT(SPACE(10)+CAST(P.IntDrRateDef-M.IntDrRate AS VARCHAR(10)),10)),RIGHT(SPACE(10)+CAST('0' AS VARCHAR(10)),10)) from Master M, ParaTable P 
where M.BranchCode=P.BranchCode and M.AcType=P.AcType and M.CyCode=P.CyCode
and M.MainCode = Master.MainCode) id_dr_pref_pcnt                        ,
RIGHT(SPACE(10)+CAST('0' AS VARCHAR(10)),10)) chnl_cr_pref_pcnt                                      ,
RIGHT(SPACE(10)+CAST('0' AS VARCHAR(10)),10)) chnl_dr_pref_pcnt                                      ,
'N' Pegged_flg                                             ,
' ' peg_frequency_in_months                                ,
' ' peg_frequency_in_days                                  ,
' ' int_freq_type_cr                                       ,		--need to discuss
' ' int_freq_week_num_cr                                   ,
' ' int_freq_week_day_cr                                   ,
' ' int_freq_start_dd_cr                                   ,
' ' int_freq_hldy_stat_cr                                  ,
' ' next_int_run_date_cr                                   ,
'D' int_freq_type_dr                                       ,		--need to discuss
' ' int_freq_week_num_dr                                   ,
' ' int_freq_week_day_dr                                   ,
' ' int_freq_start_dd_dr                                   ,
'S' int_freq_hldy_stat_dr                                  ,
' ' next_int_run_date_dr                                   ,  --BOD DATE
' ' ledg_num                                               ,
' ' emp_id                                                 ,
convert(varchar,AcOpenDate,105) acct_opn_date                                          ,
' ' Mode_of_oper_code                                      ,
' ' Gl_sub_head_code                                       ,
' ' Schm_code                                              ,
'Y' Chq_alwd_flg                                           ,
'S' Pb_ps_code                                             ,
case when IsBlocked in('B','T','D') then 'T' 
when IsBlocked ='-' then 'C' 
when IsBlocked ='+' then 'D' 
else ' ' end Frez_code                         ,		
case when IsBlocked in ('B' ,'T', 'D','-','+') then 'OTH' else ' ' end Frez_reason_code   ,  --after BPD
' ' free_text                ,
case when IsDormant ='T' then 'D' else 'A' end acct_Status                                            ,
' ' free_code_1                                            ,
' ' free_code_2                                            ,
' ' free_code_3                                            ,
' ' free_code_4                                            ,
' ' free_code_5                                            ,
' ' free_code_6                                            ,
' ' free_code_7                                            ,
' ' free_code_8                                            ,
' ' free_code_9                                            ,
' ' free_code_10                                           ,
' ' int_tbl_code                                           ,
' ' acct_loc_code                                          ,
c.CyDesc acct_crncy_code          ,	
BranchCode sol_id                                                 ,
'UBSADMIN' acct_mgr_user_id                                       ,
Name acct_name                                              ,
'Y'  swift_allowed_flg                                      ,
isnull(convert(varchar,LastTranDate,105),convert(varchar,AcOpenDate,105)) last_tran_date                                         ,
isnull((select MAX(convert(varchar,T.TranDate,105)) from TransDetail T where T.MainCode=Master.MainCode), convert(varchar,AcOpenDate,105)) last_any_tran_date                                     ,
'N' xclude_for_comb_stmt                                   ,
' ' stmt_cust_id                                           ,
' ' chrg_level_code                                        ,
' ' pbf_download_flg                                       ,
'A' wtax_level_flg                                         ,
' ' sector_code                                            ,
' ' sub_sector_code                                        ,
' ' purpose_of_advn                                        ,
' ' nature_of_advn                                         ,
' ' industry_type                                          ,
' ' int_dr_acct_flg                                        ,
' ' int_dr_acid                                            ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17 sanct_lim                                              ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17 Drwng_power                                            ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17 dacc_lim_abs                                           ,
RIGHT(SPACE(8)+CAST('0' AS VARCHAR(8)),8) dacc_lim_pcnt                                          ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) max_alwd_advn_lim                                      ,
' ' health_code                                            ,
' ' sanct_levl_code                                        ,
' ' sanct_ref_num                                          ,
convert(varchar,AcOpenDate,105) lim_sanct_date                                         ,
convert(varchar,LimitExpiryDate,105) lim_exp_date                                           ,
convert(varhcar,dateadd(dd,-30,LimitExpiryDate),105) lim_review_date                                        ,
convert(varchar,dateadd(dd,-30,LimitExpiryDate),105) loan_paper_date                                        ,
' ' sanct_auth_code                                        ,
' ' ecgc_appl_flg                                          ,
' ' ecgc_dr_acid                                           ,
' ' due_date                                               ,
' ' rpc_acct_flg                                           ,
' ' disb_ind                                               ,
' ' Compound_date                                          ,
' ' daily_comp_int_flg                                     ,
' ' COMP_Date_flg                                          ,
' ' disc_rate_flg                                          ,		--need to discuss
' ' dummy                                                  ,
case when IsDormant='T' then convert(varchar,dateadd(MM,6,isnull(LastTranDate,AcOpenDate)),105) else ' ' end acct_status_date                                       ,
' ' iban_number                                            ,
' ' ias_code                                               ,
' ' channel_id                                             ,
' ' channel_level_code                                     ,
' ' int_suspense_amt                                       ,		--after bpd
' ' Penal_int_Suspense_amt                                 ,		--after bpd
'Y' Chrge_off_flg                                          ,		--need to discuss
'Y' pd_flg                                                 ,
' ' pd_xfer_Date											,		--need to discuss
' ' Chrge_off_date                                         ,		--need to discuss
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS Chrge_off_principal                                    ,		
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS Pending_interest                                       ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS Principal_recovery                                     ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS interest_recovery                                      ,
' ' Charge_off_type                                        ,		--need to discuss
' ' master_acct_num                                        ,
'D' penal_prod_mthd_flg                                    ,
'D' penal_rate_mthd_flg                                    ,
' ' waive_min_coll_int                                     ,
' ' rule_code                                              ,
' ' ps_diff_freq_rel_party_flg                             ,
' ' swift_diff_freq_rel_party_flg                          ,
' ' add_type                                               ,
' ' Phone_type                                             ,
' ' Email_type                                             ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS accrued_penal_int_recovery                             ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS penal_int_recovery                                     ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS coll_int_recovery                                      ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS coll_penal_int_recovery                                ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS pending_penal_interest                                 ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS pending_penal_booked_interest                          ,
' ' int_rate_prd_in_months                                 ,
' ' int_rate_prd_in_days                                   ,
' ' penal_int_tbl_code                                     ,
RIGHT(SPACE(9)+CAST('0' AS VARCHAR(9)),9) AS penal_pref_pcnt                                        ,
' ' interpolation_method                                   ,
' ' hedged_acct_flg                                        ,
' ' used_for_net_off_flg                                   ,
' ' alt1_acct_name                                         ,
' ' security_indicator                                     ,
' ' debt_seniority                                         ,
' ' security_code                                          ,
' ' Debit_Interest_Method                                  ,
' ' Service_chrge_collection_flg                           ,
convert(varchar,dateadd(dd, -1 , AcOpenDate),105) Last_purge_date                                        ,		--need to discuss
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AStotal_project_cost                                     ,
' ' loss_carry_fwd                                         ,
' ' unadj_profit_carry_fwd                                 ,
' ' collect_excess_profit                                  ,
' ' adj_order_for_carry_fwd                                ,
RIGHT(SPACE(9)+CAST('0' AS VARCHAR(9)),9) AS bank_profit_share_pcnt                                 ,
RIGHT(SPACE(9)+CAST('0' AS VARCHAR(9)),9) AS bank_loss_share_pcnt                                   ,
' ' profit_adj_freq_type                                   ,
' ' profit_adj_freq_week_num                               ,
' ' profit_adj_freq_week_day                               ,
' ' profit_adj_freq_start_dd                               ,
' ' profit_adj_freq_hldy_stat                              ,
' ' next_profit_adj_due_date                               ,
RIGHT(SPACE(9)+CAST('0' AS VARCHAR(9)),9) AS  tot_bank_captl_share_pcnt                              ,
' ' profit_adj_grace_prd_mths                              ,
' ' profit_adj_grace_prd_days                              ,
' ' adj_cycle_end_date                                     ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS unadj_profit_carry_fwd_amt                             ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS unadj_profit_settle_amt                                ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS unadj_profit_charge_off_amt                            ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS loss_carry_fwd_amt                                     ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS loss_settle_amt                                        ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS loss_charge_off_amt                                    ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS profit_adj_amt                                         ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS loss_adj_amt                                           ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS tot_expected_profit_amt                                ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS bank_profit_share_amt                                  ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS bank_loss_share_amt                                    ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS actual_profit_amt                                      ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS actual_loss_amt                                        ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS collected_amt                                          ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS excess_profit_collected_amt                            ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17) AS broken_prd_prft_in_legacy                              ,
' ' unclaim_status                                         ,
' ' unclaim_status_date                                    ,
' ' orig_gl_sub_head_code                                  ,
' ' pais_applicable_flg                                    ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17)as pais_bank_amt                                          ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17)as pais_cust_amt                                          ,
RIGHT(SPACE(17)+CAST('0' AS VARCHAR(17)),17)as pais_debited_amt                                       ,
' ' pais_effective_date                                    ,
' ' pais_coverage_end_date                                 ,
' ' primary_crop_code                                      ,
' ' primary_crop_state_code                                ,
' ' primary_no_of_crop_in_year 
from Master m left join CurrencyTable c on m.CyCode = c.CyCode
where left(ClientCode,1)<>'_'
--where AcType in  ('01', '02', '03', '04', '06', '28', '29', '3C', '3D', '3G', '3H', '3I', '3J', '3W', '4H', '4L', '4N', '4R')
--where AcType in ('06', '3C', '3D', '3G', '3H', '3I', '3J', '3W', '4H', '4L', '4N', '4R') ODA only.
