select 
distinct 'CO'+ClientCode as CORP_KEY
,'CO'+ClientCode as CIFID
,'' as CORP_REP_KEY
,'CURRENCY' as TYPE
,case when  CyCode='01' then 'NPR' when CyCode='21' then 'USD' end as STR1
,'' as STR2
,'' as STR3
,'' as STR4
,'' as STR5
,'' as STR6
,'' as STR7
,'' as STR8
,'' as STR9
,'' as STR10
,'' as STR11
,'31-12-2099' as DATE1
,'' as STR12
,'' as DATE2
,0 as AMOUNT1
,'' as AMOUNT2
,'' as AMOUNT3
,'' as AMOUNT4
,'' as SMALL_STR1
,'' as SMALL_STR2
,'' as SMALL_STR3
,'' as SMALL_STR4
,'' as SMALL_STR5
,'' as SMALL_STR6
,'' as SMALL_STR7
,'' as SMALL_STR8
,'' as SMALL_STR9
,'' as SMALL_STR10
,'' as MED_STR1
,'' as MED_STR2
,'' as MED_STR3
,'' as MED_STR4
,'' as MED_STR5
,'' as MED_STR6
,'' as MED_STR7
,'' as MED_STR8
,'' as MED_STR9
,'' as MED_STR10
,'' as LARGE_STR1
,'' as LARGE_STR2
,'' as LARGE_STR3
,'' as LARGE_STR4
,'' as LARGE_STR5
,'' as DATE3
,'' as DATE4
,'' as DATE5
,'' as DATE6
,'' as DATE7
,'' as DATE8
,'' as DATE9
,'' as DATE10
,'' as NUMBER1
,'' as NUMBER2
,'' as NUMBER3
,'' as NUMBER4
,'' as NUMBER5
,'' as NUMBER6
,'' as NUMBER7
,'' as NUMBER8
,'' as NUMBER9
,'' as NUMBER10
,'' as DECIMAL1
,'' as DECIMAL2
,'' as DECIMAL3
,'' as DECIMAL4
,'' as DECIMAL5
,'' as DECIMAL6
,'' as DECIMAL7
,'' as DECIMAL8
,'' as DECIMAL9
,'' as DECIMAL10
,'CUSTOMER' as ENTITYTYPE
,'' as STR43
,'' as STR44
,'' as STR45
,'' as STR46
,'' as STR47
,'' as STR48
,'' as STR49
,'' as STR50
,'CO'+ClientCode as ORGKEY
,'' as STR21
,'' as STR22
,'' as STR23
,'' as STR24
,'' as STR25
,'' as STR26
,'' as STR27
,'' as STR28
,'' as STR29
,'' as STR30
,'' as STR31
,'' as STR32
,'' as STR38
,'' as STR39
,'' as STR40
,'' as STR41
,'' as STR42
,'' as DBFLOAT1
,'' as DBFLOAT2
,'' as DBFLOAT3
,'' as DBFLOAT4
,'' as DBFLOAT5
,'' as AMOUNT5
,'' as FLAG1
,'' as FLAG2
,'' as FLAG3
,'' as FLAG4
,'' as FLAG5
,'' as INT1
,'' as INT2
,'' as INT3
,'' as INT4
,'' as INT5
,'' as INT6
,'' as INT7
,'' as INT8
,'' as INT9
,'' as INT10
,'' as INT11
,'' as INT12
,'' as INT13
,'' as INT14
,'' as INT15
,'' as MLUSERFIELD1
,'' as MLUSERFIELD2
,'' as MLUSERFIELD3
,'' as MLUSERFIELD4
,'' as MLUSERFIELD5
,'' as STR1_CODE
,'' as STR2_CODE
,'' as STR3_CODE
,'' as STR4_CODE
,'' as STR5_CODE
,NULL as CORE_CUST_ID
,'' as CORE_CHILD_CUST_ID
,0 as PERCENTAGE1
,0 as PERCENTAGE2
,0 as PERCENTAGE3
,'' as PERCENTAGE4
,'' as PERCENTAGE5
,'SNMANPKA' as BANK_ID
,'' as STR4_ALT1
,'' as STR5_ALT1
,'' as STR1_ALT1
from Master
WHERE t1.IsBlocked NOT IN ('C','o')  -- Filters the closed or invalid or unapproved accounts
and MainCode in
(select MainCode from AcCustType where CustTypeCode='Z' and CustType not in ('11','12') )