--select top 1 * from Master

IF OBJECT_ID('tempdb.dbo.#FinalMaster', 'U') IS NOT NULL
  DROP TABLE #FinalMaster;			-- Drop temporary table if it exists
SELECT * INTO #FinalMaster FROM
(
	SELECT DISTINCT
	 ClientCode
	,MainCode
	,AcOpenDate
	,ROW_NUMBER() OVER( PARTITION BY ClientCode ORDER BY AcOpenDate, MainCode) AS SerialNumber
	--INTO #FinalMaster
	FROM Master WITH (NOLOCK)
	WHERE IsBlocked NOT IN ('C','o')  -- Filters the closed or invalid or unapproved accounts
	--ORDER BY ClientCode
) AS t 
WHERE t.SerialNumber = 1 ORDER BY 1;


SELECT DISTINCT 
'C0' + t1.ClientCode AS CORP_KEY
,'C0' + t1.ClientCode AS CIFID
,'C0' + t1.ClientCode AS CORP_REP_KEY
,'' AS GENDER_CODE
--,CASE WHEN ct.DateOfBirth IS NULL OR ct.DateOfBirth = '' THEN '01-Jan-1980'
 -- ELSE  REPLACE(REPLACE(CONVERT(VARCHAR,ct.DateOfBirth,106), ' ','-'), ',','') 
 -- END AS DOB
, '01-Jan-1980' AS DOB
,'' AS DESIGNATION
,'Y' AS ACTIVE_INACTICE_CODE		--mandatory field
,'' AS SMALL_STR1
,'' AS SMALL_STR2
,'' AS SMALL_STR3
,'' AS SMALL_STR4
,'' AS SMALL_STR5
,'' AS SMALL_STR6
,'' AS SMALL_STR7
,'' AS SMALL_STR8
,'' AS SMALL_STR9
,'' AS SMALL_STR10
,'' AS MED_STR1
,'' AS MED_STR2
,'' AS MED_STR3
,'' AS MED_STR4
,'' AS MED_STR5
,'' AS MED_STR6
,'' AS MED_STR7
,'' AS MED_STR8
,'' AS MED_STR9
,'' AS MED_STR10
,'' AS LARGE_STR1
,'' AS LARGE_STR2
,'' AS LARGE_STR3
,'' AS LARGE_STR4
,'' AS LARGE_STR5
,'' AS DATE1
,'' AS DATE2
,'' AS DATE3
,'' AS DATE4
,'' AS DATE5
,'' AS DATE6
,'' AS DATE7
,'' AS DATE8
,'' AS DATE9
,'' AS DATE10
,'' AS NUMBER1
,'' AS NUMBER2
,'' AS NUMBER3
,'' AS NUMBER4
,'' AS NUMBER5
,'' AS NUMBER6
,'' AS NUMBER7
,'' AS NUMBER8
,'' AS NUMBER9
,'' AS NUMBER10
,'' AS DECIMAL1
,'' AS DECIMAL2
,'' AS DECIMAL3
,'' AS DECIMAL4
,'' AS DECIMAL5
,'' AS DECIMAL6
,'' AS DECIMAL7
,'' AS DECIMAL8
,'' AS DECIMAL9
,'' AS DECIMAL10
,'C0' + t1.ClientCode AS ENTITYKEY   --mandatory field(CIF ID of the corporate representative.)
,'' AS ISSIGNATORY
,'Registered' AS CIFADDRENTITY		--mandatory field 'Registered'
,'Registered' AS ADDRESSCATEOGRY
,'' AS FIRST_NAME_NATIVE
,'' AS LAST_NAME_NATIVE
,'' AS CORPORATE_NAME_NATIVE
,'' AS FIRST_NAME
,'.' AS LAST_NAME			--mandatory field
,'' AS EMAIL_ID
,'CUST' AS ENTITY_TYPE
,'' AS QUALIFICATION
,'MIGR' AS PREF_COMM_CHANNEL
,'MIGR' AS REPORTS_TO
,'' AS PREF_LANGUAGE
,'' AS PREF_CONTACT_NUMBER
,'' AS PREF_CONTACT_TIME
,'' AS PREF_NAME
,'' AS PREF_ADDRESS_MODE
,'M/S.' AS SALUATION_CODE
,'' AS STR1
,'' AS STR2
,'' AS STR3
,'' AS STR4
,'' AS STR5
,'' AS STR6
,'' AS STR7
,'' AS STR8
,'' AS STR9
,'' AS STR10
,'' AS STR11
,'' AS STR12
,'' AS STR13
,'' AS STR14
,'' AS STR15
,'' AS AMOUNT1
,'' AS AMOUNT2
,'' AS AMOUNT3
,'' AS AMOUNT4
,'' AS AMOUNT5
,'' AS FLAG1
,'' AS FLAG2
,'' AS FLAG3
,'' AS FLAG4
,'' AS FLAG5
,'' AS INT1
,'' AS INT2
,'' AS INT3
,'' AS INT4
,'' AS INT5
,'' AS MLUSERFIELD1
,'' AS MLUSERFIELD2
,'' AS MLUSERFIELD3
,'' AS MLUSERFIELD4
,'' AS MLUSERFIELD5
,'' AS MLUSERFIELD6
,'' AS MLUSERFIELD7
,'' AS MLUSERFIELD8
,'' AS MLUSERFIELD9
,'' AS MLUSERFIELD10
,'01' AS BANK_ID
,'' AS LAST_NAME_ALT1
,'' AS FIRST_NAME_ALT1
FROM #FinalMaster t1
LEFT JOIN ClientTable ct ON t1.ClientCode=ct.ClientCode
WHERE t1.MainCode in
(
	SELECT MainCode FROM AcCustType WHERE CustTypeCode = 'Z' AND CustType NOT IN ('11','12')
)
ORDER BY CORP_KEY